import {cpSync,existsSync,mkdirSync} from 'node:fs';
import {dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
const here=dirname(fileURLToPath(import.meta.url));
const source=join(here,'../data/derived/v2');
if(!existsSync(join(source,'catalog.json')))throw new Error('Missing committed v2 catalogue; run scripts/precompute first.');
mkdirSync(join(here,'public-release/data/v2'),{recursive:true});
cpSync(source,join(here,'public-release/data/v2'),{recursive:true});
cpSync(join(here,'public/svg'),join(here,'public-release/svg'),{recursive:true});
console.log('Copied canonical v2 experiments and checkpoints. No computation in build.');
