import { useEffect, useMemo, useRef, useState } from "react";
import { FWI_METHODS, readFwiFiles, type FwiAdmission, type FwiMethod } from "../api/fwi-local-contracts";
import { Heatmap, Plot } from "./ScientificPlots";
import { downloadInspection } from "./result-view-data";
import { format } from "../science";

function matrix(values:Float32Array, rows:number, cols:number, offset=0){
  return Array.from({length:rows},(_,row)=>Array.from(values.subarray(offset+row*cols,offset+(row+1)*cols)));
}

export function FwiLocalInstrument({admitted,es}:{admitted:FwiAdmission;es:boolean}){
  const t=(en:string,sp:string)=>es?sp:en;
  const [method,setMethod]=useState<FwiMethod>("fwi-multiscale"),[frame,setFrame]=useState(-1),[shot,setShot]=useState(0),[receiver,setReceiver]=useState(0),[sample,setSample]=useState(0),[cell,setCell]=useState(0),[view,setView]=useState("model"),[playing,setPlaying]=useState(false),[velocityScale,setVelocityScale]=useState("returned");
  const {manifest:m,arrays}=admitted,q=m.request,state=m.methods[method];
  const [shots,receivers,samples]=q.observed.shape,frames=m.arrays[method+"-frames"].shape[0],selectedFrame=frame<0?frames-1:Math.min(frame,frames-1),iteration=state.frame_history_indices[selectedFrame];
  useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setFrame(value=>{const next=(value<0?frames-1:value)+1;if(next>=frames){setPlaying(false);return frames-1;}return next;}),500);return()=>clearInterval(timer);},[playing,frames]);
  const model=useMemo(()=>matrix(arrays[method+"-frames"],96,128,selectedFrame*96*128),[arrays,method,selectedFrame]);
  const initial=useMemo(()=>matrix(arrays.initial,96,128),[arrays]);
  const returnedRange=useMemo<[number,number]>(()=>{let low=Infinity,high=-Infinity;for(const name of ["initial",method+"-frames"])for(const value of arrays[name]){low=Math.min(low,value);high=Math.max(high,value);}const pad=Math.max(1,(high-low)*.02);return [low-pad,high+pad];},[arrays,method]);
  const velocityRange:[number,number]=velocityScale==="returned"?returnedRange:[1400,4400];
  const time=useMemo(()=>Array.from({length:samples},(_,index)=>index*q.acquisition.dt_s),[samples,q.acquisition.dt_s]);
  const receiverCoordinates=q.acquisition.receivers_m.map(point=>point[0]);
  const receiverRange:[number,number]=[receiverCoordinates[0]-(receiverCoordinates[1]-receiverCoordinates[0])/2,receiverCoordinates[receivers-1]+(receiverCoordinates[receivers-1]-receiverCoordinates[receivers-2])/2];
  const timeExtentLabel=`t [s] · 0 → ${time[samples-1].toFixed(4)}`;
  const datum=(shot*receivers+receiver)*samples+sample;
  const slice=(name:string)=>Array.from(arrays[name].subarray((shot*receivers+receiver)*samples,(shot*receivers+receiver+1)*samples));
  const gather=(name:string)=>Array.from({length:samples},(_,row)=>Array.from({length:receivers},(_,column)=>arrays[name][(shot*receivers+column)*samples+row]));
  const amplitude=useMemo(()=>{let maximum=0;for(const name of ["observed",method+"-predicted",method+"-residual"])for(const value of arrays[name])maximum=Math.max(maximum,Math.abs(value));return maximum||1;},[arrays,method]);
  const traceAmplitude=useMemo(()=>{let maximum=0;for(const name of ["observed",method+"-predicted",method+"-residual"])for(const value of arrays[name].subarray((shot*receivers+receiver)*samples,(shot*receivers+receiver+1)*samples))maximum=Math.max(maximum,Math.abs(value));return (maximum||1)*1.05;},[arrays,method,shot,receiver,receivers,samples]);
  const changeMethod=(value:FwiMethod)=>{setMethod(value);setFrame(-1);setPlaying(false);};
  const numeric=(label:string,value:number,min:number,max:number,set:(n:number)=>void)=><label className="select-control"><span>{label}</span><input type="number" min={min} max={max} step="1" value={value} onChange={e=>{const n=e.target.valueAsNumber;if(Number.isInteger(n)&&n>=min&&n<=max)set(n);}}/></label>;
  return <article data-testid="fwi-local-instrument">
    <h2>{q.id} · {t("Supplied acoustic inversion", "Inversión acústica suministrada")}</h2>
    <p className="plot-note">{t("Original local bytes verified. The browser inspects returned arrays; it does not rerun the acoustic propagator or submit a VPS job. A hash manifest is not a signature. No known field truth.","Bytes locales originales verificados. El navegador inspecciona matrices devueltas; no ejecuta propagador acústico ni envía tarea al VPS. Un manifiesto de hashes no es firma. Sin verdad de campo conocida.")}</p>
    <div className="processing-view-controls">
      <label className="select-control"><span>{t("FWI schedule","Programa FWI")}</span><select aria-label={t("FWI schedule","Programa FWI")} className="select" value={method} onChange={e=>changeMethod(e.target.value as FwiMethod)}>{FWI_METHODS.map(value=><option key={value} value={value}>{value==="fwi-l2"?t("Full-band after shared background","Banda completa tras fondo compartido"):t("Frequency continuation","Continuación de frecuencia")}</option>)}</select></label>
      <label className="select-control"><span>{t("Scientific view","Vista científica")}</span><select aria-label={t("Scientific view","Vista científica")} className="select" value={view} onChange={e=>setView(e.target.value)}>{[["model",t("Velocity iterations","Iteraciones de velocidad")],["gathers",t("Observed / predicted / residual gathers","Registros observados / predichos / residuales")],["trace",t("Linked full-sample trace","Traza vinculada con todas las muestras")],["objective",t("Evaluated objective and holdout","Objetivo evaluado y reserva")]].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
      {numeric(t("Source shot index","Índice de disparo"),shot,0,shots-1,setShot)}
      {numeric(t("Original receiver index","Índice original de receptor"),receiver,0,receivers-1,setReceiver)}
      {numeric(t("Original time-sample index","Índice original de muestra temporal"),sample,0,samples-1,setSample)}
    </div>
    <output className="processing-value-readout" data-testid="fwi-exact-sample">S={shot} R={receiver} x={q.acquisition.receivers_m[receiver][0]} m · t={time[sample].toFixed(4)} s · {t("observed","observado")}={format(arrays.observed[datum])} · {t("predicted","predicho")}={format(arrays[method+"-predicted"][datum])} · Δ={format(arrays[method+"-residual"][datum])} [point-source-amplitude] · {m.active_receivers[receiver]?t("fitted receiver","receptor ajustado"):t("withheld receiver","receptor reservado")}</output>
    {view==="model"&&<>
      <div className="processing-view-controls">
        <label className="select-control"><span>{t("Recorded velocity state","Estado de velocidad registrado")}</span><input aria-label={t("Recorded velocity state","Estado de velocidad registrado")} type="range" min="0" max={frames-1} value={selectedFrame} onChange={e=>{setPlaying(false);setFrame(Number(e.target.value));}}/></label>
        <button className="btn" onClick={()=>{if(selectedFrame===frames-1)setFrame(0);setPlaying(!playing);}}>{playing?t("Pause recorded iterations","Pausar iteraciones registradas"):t("Play recorded iterations","Reproducir iteraciones registradas")}</button>
        {numeric(t("Native velocity cell index","Índice nativo de celda de velocidad"),cell,0,96*128-1,setCell)}
        <label className="select-control"><span>{t("Velocity colour range","Rango de color de velocidad")}</span><select className="select" aria-label={t("Velocity colour range","Rango de color de velocidad")} value={velocityScale} onChange={e=>setVelocityScale(e.target.value)}><option value="returned">{t("Shared initial / all returned states","Inicial / todos los estados devueltos compartidos")}</option><option value="bounds">{t("Full physical bounds","Límites físicos completos")}</option></select></label>
      </div>
      <p>{t("Recorded state","Estado registrado")} {selectedFrame}/{frames-1} · {t("evaluated history index","índice de historial evaluado")} {iteration} · {String(state.history_records[iteration].phase)} · v={model[Math.floor(cell/128)][cell%128]} m/s · v₀={arrays.initial[cell]} m/s · Δv={model[Math.floor(cell/128)][cell%128]-arrays.initial[cell]} m/s · x={(cell%128)*12.5} m · z={Math.floor(cell/128)*12.5} m</p>
      <div className="two-plots">{[{data:initial,title:t("Supplied independent initial velocity","Velocidad inicial independiente suministrada")},{data:model,title:t("Returned native acoustic velocity","Velocidad acústica nativa devuelta")}].map(item=><Heatmap key={item.title} data={item.data} title={item.title} unit="m/s" palette="velocity" range={velocityRange} aspectRatio={128/96} xLabel="x [m]" yLabel={t("depth [m] · down","profundidad [m] · abajo")} xRange={[-6.25,1593.75]} yRange={[-6.25,1193.75]} xCoordinates={Array.from({length:128},(_,i)=>i*12.5)} yCoordinates={Array.from({length:96},(_,i)=>i*12.5)} onPick={(x,z)=>setCell(z*128+x)}/>)}</div>
      <p className="plot-note">{t("Replaying velocity iterations does not recompute waveforms. Gathers, residuals and linked trace values refer to the evaluated terminal model.","Reproducir iteraciones de velocidad no recalcula ondas. Registros, residuales y valores vinculados corresponden al modelo terminal evaluado.")}</p>
    </>}
    {view==="gathers"&&<div className="three-plots">{["observed",method+"-predicted",method+"-residual"].map(name=><Heatmap key={name} data={gather(name)} title={name==="observed"?t("Original observed shot gather","Registro de disparo observado original"):name.endsWith("-predicted")?t("Terminal-model prediction","Predicción del modelo terminal"):t("Signed observed-minus-predicted residual","Residual con signo observado menos predicho")} unit="point-source-amplitude" palette="field" range={[-amplitude,amplitude]} aspectRatio={1.45} xLabel={t("receiver x [m]","receptor x [m]")} yLabel={timeExtentLabel} xRange={receiverRange} yRange={[0,time[samples-1]]} xCoordinates={receiverCoordinates} yCoordinates={time} cursorY={sample/(samples-1)} onPick={(r,s)=>{setReceiver(r);setSample(s);}}/>)}</div>}
    {view==="trace"&&<Plot interactive selectedIndex={sample} onSelect={setSample} x={time} series={[{name:t("Observed","Observado"),values:slice("observed")},{name:t("Predicted","Predicho"),values:slice(method+"-predicted")},{name:t("Residual","Residual"),values:slice(method+"-residual"),dashed:true}]} title={t("Exact supplied trace and terminal prediction","Traza exacta suministrada y predicción terminal")} xLabel="t [s]" yLabel="point-source-amplitude" zeroCentered fixedYRange={[-traceAmplitude,traceAmplitude]}/>}
    {view==="objective"&&<Plot interactive selectedIndex={iteration} x={state.history_records.map((_,index)=>index)} series={[{name:t("Stage objective","Objetivo de etapa"),values:state.history_records.map(record=>Number(record.objective))},{name:t("Fitted relative MSE","MSE relativo ajustado"),values:state.history_records.map(record=>Number(record.active_relative_mse))},{name:t("Withheld relative MSE","MSE relativo reservado"),values:state.history_records.map(record=>Number(record.withheld_relative_mse)),dashed:true}]} title={t("Evaluated states; frequency/grid changes between stages","Estados evaluados; frecuencia/malla cambian entre etapas")} xLabel={t("evaluated history index [1]","índice de historial evaluado [1]")} yLabel="[1]"/>}
    <p>{t("Stopping: finite iteration budget, not a stationarity certificate. Relative waveform error is not velocity recovery. Neither field suitability nor a unique subsurface model is established.","Parada: presupuesto finito de iteraciones, no certificado de estacionariedad. Error relativo de ondas no es recuperación de velocidad. No establece aptitud de campo ni modelo único del subsuelo.")}</p>
    <details className="processing-provenance"><summary>{t("Exact source, solver and measured resources","Fuente, solver y recursos medidos exactos")}</summary><p>{q.source.citation} · {q.source.rights} · {q.source.scope}</p><pre>{JSON.stringify({originals:m.originals,parameters:q.parameters,solver:state.solver,metrics:state.metrics,environment:m.environment,resources:m.resources,source_hashes:m.source_hashes},null,2)}</pre><p>SHA256 manifest {admitted.manifestSha256}</p></details>
    <button className="btn" onClick={()=>downloadInspection({schema:"geophysics.fwi-inspection/v1",inspection_only:true,physics_replayed:false,manifest_sha256:admitted.manifestSha256,method,frame:selectedFrame,history_index:iteration,shot,receiver,sample,time_s:time[sample],observed:arrays.observed[datum],predicted:arrays[method+"-predicted"][datum],residual:arrays[method+"-residual"][datum],cell,velocity_m_s:model[Math.floor(cell/128)][cell%128]},"local-fwi-inspection.json")}>{t("Export exact FWI inspection JSON","Exportar inspección FWI exacta JSON")}</button>
  </article>;
}

export function FwiLocalWorkbench({es,onCurated}:{es:boolean;onCurated:()=>void}){
  const t=(en:string,sp:string)=>es?sp:en;
  const [files,setFiles]=useState<File[]>([]),[admitted,setAdmitted]=useState<FwiAdmission|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[controls,setControls]=useState(false);
  const epoch=useRef(0);useEffect(()=>()=>{epoch.current++;},[]);
  const open=async()=>{const current=++epoch.current;setBusy(true);setError("");try{const result=await readFwiFiles(files);if(current===epoch.current){setAdmitted(result);setControls(false);}}catch{if(current===epoch.current)setError(t("Files rejected; the last verified result is unchanged. Select manifest.json and all twelve .f32 members from one complete generation.","Archivos rechazados; último resultado verificado sin cambios. Seleccione manifest.json y los doce miembros .f32 de una generación completa."));}finally{if(current===epoch.current)setBusy(false);}};
  return <div className="page-body wide workbench processing-workbench"><aside className={`instrument-sidebar processing-sidebar ${controls?"expanded":""}`}>
    <div className="instrument-brand"><div><span className="small-caps">{t("LOCAL FILES · NO UPLOAD","ARCHIVOS LOCALES · SIN CARGA")}</span><h1>{t("Acoustic FWI results","Resultados FWI acústicos")}</h1></div></div>
    <button className="btn mobile-controls-toggle" aria-expanded={controls} onClick={()=>setControls(!controls)}>{t("Local acoustic controls","Controles acústicos locales")}</button>
    <div className="processing-controls"><button className="btn" onClick={onCurated}>{t("Curated cases","Casos curados")}</button><label className="select-control"><span>{t("Complete local acoustic generation","Generación acústica local completa")}</span><input type="file" multiple accept=".json,.f32" onChange={e=>{epoch.current++;setBusy(false);setError("");setFiles(Array.from(e.target.files??[]));}}/></label><button className="btn" disabled={busy||files.length!==13} onClick={()=>void open()}>{t("Open verified acoustic result","Abrir resultado acústico verificado")}</button>{busy&&<p role="status">{t("Verifying every original sample and saved state…","Verificando cada muestra original y estado guardado…")}</p>}{error&&<p role="alert">{error}</p>}<p className="plot-note">{t("Run scripts/process_fwi.py locally with CPU or CUDA. Files remain in your browser; no account, upload, server solve or training.","Ejecute scripts/process_fwi.py localmente con CPU o CUDA. Archivos permanecen en navegador; sin cuenta, carga, cálculo en servidor ni entrenamiento.")}</p></div>
  </aside><section className="instrument-main processing-main" aria-label={t("Local acoustic inspection","Inspección acústica local")}>{admitted?<FwiLocalInstrument key={admitted.manifestSha256} admitted={admitted} es={es}/>:<p>{t("Select all thirteen files from a completed original-data generation. No example is substituted automatically.","Seleccione los trece archivos de una generación de datos originales completa. No se sustituye automáticamente un ejemplo.")}</p>}</section></div>;
}
