import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { ApiClient, ApiHttpError } from "../api/client";
import { LifecycleApi, type ProjectView } from "../api/lifecycle";
import type { RawAsset } from "../api/contracts";
import { MtProcessingApi } from "../api/mt-processing";
import { validateMtParameters, type EdiDataset, type MtResult } from "../api/mt-contracts";
import { M05_METHOD, M06_METHOD, isFlagJob, isGravityReceipt, type EdiDatasetReceipt, type MethodEligibility, type ProjectProcessingJob, type ProcessingState } from "../api/processing-contracts";
import { MtScientificInstrument } from "./MtScientificInstrument";

const active=(job:ProjectProcessingJob)=>job.state==="queued"||job.state==="running";
export function MtProjectWorkbench({projectId,es,onManage,onCurated,onGravity}:{projectId:string;es:boolean;onManage:()=>void;onCurated:()=>void;onGravity:()=>void}) {
  const t=(en:string,sp:string)=>es?sp:en;
  const clients=useMemo(()=>{const c=new ApiClient(window.location.origin);return {life:new LifecycleApi(c),mt:new MtProcessingApi(c)};},[]);
  const [project,setProject]=useState<ProjectView|null>(null),[assets,setAssets]=useState<RawAsset[]>([]),[receipts,setReceipts]=useState<EdiDatasetReceipt[]>([]),[jobs,setJobs]=useState<ProjectProcessingJob[]>([]);
  const [session,setSession]=useState("checking"),[assetId,setAssetId]=useState(""),[datasetId,setDatasetId]=useState(""),[jobId,setJobId]=useState("");
  const [dataset,setDataset]=useState<EdiDataset|null>(null),[eligibility,setEligibility]=useState<MethodEligibility|null>(null),[result,setResult]=useState<MtResult|null>(null);
  const [section,setSection]=useState("data"),[method,setMethod]=useState<typeof M05_METHOD|typeof M06_METHOD>(M05_METHOD),[two,setTwo]=useState(false),[h,setH]=useState("350"),[rho,setRho]=useState("100"),[basement,setBasement]=useState("100"),[beta,setBeta]=useState("0.001"),[draws,setDraws]=useState("20"),[seed,setSeed]=useState("61001");
  const [revision,setRevision]=useState(0),[pollRetry,setPollRetry]=useState(0),[busy,setBusy]=useState(false),[expanded,setExpanded]=useState(false),[problem,setProblem]=useState<unknown>(null),[pollError,setPollError]=useState<unknown>(null),[notice,setNotice]=useState("");
  const lifetime=useRef(new AbortController()),owner=useRef("");
  const clear=()=>{setProject(null);setAssets([]);setReceipts([]);setJobs([]);setDataset(null);setEligibility(null);setResult(null);};
  const fail=(e:unknown)=>{if(e instanceof ApiHttpError&&e.status===401){lifetime.current.abort();clear();setSession("expired");}setProblem(e);};
  const message=(e:unknown)=>e instanceof ApiHttpError?`${t("API rejected the action; inspect the original declarations or method admission.","La API rechazó la acción; revise declaraciones originales o admisión del método.")} (${e.code})${e.fields.length?` · ${e.fields.join(", ")}`:""}`:`${t("Data/request unavailable","Datos/solicitud no disponibles")}: ${e instanceof Error?e.message:String(e)}`;
  useEffect(()=>{
    lifetime.current=new AbortController();const {signal}=lifetime.current;clear();setSession("checking");setProblem(null);setBusy(false);
    void(async()=>{try{const account=await clients.life.probe(signal);if(signal.aborted)return;if(!account){setSession("signedout");return;}owner.current=account.id;
      const projects=await clients.life.projects(signal),p=projects.find(v=>v.id===projectId);if(!p)throw new ApiHttpError(404,"not_found","Project not found");
      const [raw,data,history]=await Promise.all([clients.life.assets(projectId,signal),clients.mt.datasets(projectId,signal),clients.mt.jobs(projectId,signal)]);
      if(raw.some(v=>v.project_id!==projectId||v.owner_id!==account.id))throw new Error("Original owner/project mismatch");if(signal.aborted)return;
      const edi=data.filter((v):v is EdiDatasetReceipt=>!isGravityReceipt(v));setProject(p);setAssets(raw.filter(v=>v.detected_format==="edi"));setReceipts(edi);setJobs(history);
      setAssetId(v=>raw.some(r=>r.asset_id===v&&r.detected_format==="edi")?v:raw.find(r=>r.detected_format==="edi")?.asset_id??"");setDatasetId(v=>edi.some(r=>r.dataset_id===v)?v:edi.at(-1)?.dataset_id??"");setSession("ready");
    }catch(e){if(!signal.aborted){fail(e);if(!(e instanceof ApiHttpError&&e.status===401))setSession("unavailable");}}})();return()=>{lifetime.current.abort();owner.current="";};
  },[clients,projectId,revision]);
  const receipt=receipts.find(v=>v.dataset_id===datasetId),history=jobs.filter(v=>!isFlagJob(v)&&v.dataset_id===datasetId),job=history.find(v=>v.job_id===jobId),hasActive=jobs.some(active);
  useEffect(()=>{setDataset(null);setEligibility(null);setResult(null);setProblem(null);setJobId("");if(session!=="ready"||!receipt)return;const c=new AbortController();
    void Promise.all([clients.mt.ediDataset(projectId,receipt,c.signal),clients.mt.methods(projectId,datasetId,c.signal)]).then(([data,verdict])=>{if(c.signal.aborted)return;if(data.owner_id!==owner.current)throw new Error("Dataset owner mismatch");setDataset(data);setEligibility(verdict);}).catch(e=>{if(!c.signal.aborted)fail(e);});return()=>c.abort();
  },[clients,receipt,session,projectId]);
  useEffect(()=>{setJobId(v=>history.some(j=>j.job_id===v)?v:history.at(-1)?.job_id??"");},[jobs,datasetId,dataset]);
  useEffect(()=>{if(session!=="ready"||!hasActive)return;const c=new AbortController();let timer:ReturnType<typeof setTimeout>;setPollError(null);
    const poll=async()=>{try{const rows=await clients.mt.jobs(projectId,c.signal);if(c.signal.aborted)return;setJobs(rows);if(rows.some(active))timer=setTimeout(poll,1000);}catch(e){if(!c.signal.aborted){if(e instanceof ApiHttpError&&e.status===401)fail(e);else setPollError(e);}}};timer=setTimeout(poll,1000);return()=>{clearTimeout(timer);c.abort();};
  },[clients,projectId,session,hasActive,pollRetry]);
  useEffect(()=>{setResult(null);if(session!=="ready"||!job||isFlagJob(job)||job.state!=="succeeded"||!dataset||!receipt)return;const c=new AbortController();
    void(async()=>{const [output,verdict]=await Promise.all([clients.mt.mtResult(projectId,job,dataset,receipt,c.signal),clients.mt.methods(projectId,datasetId,c.signal)]);if(!c.signal.aborted){setResult(output);setEligibility(verdict);}})().catch(e=>{if(!c.signal.aborted)fail(e);});return()=>c.abort();
  },[clients,projectId,job?.job_id,job?.state,job?.result_sha256,dataset,session]);
  const act=async(fn:(signal:AbortSignal)=>Promise<void>)=>{const {signal}=lifetime.current;if(signal.aborted||session!=="ready")return;setBusy(true);setProblem(null);setNotice("");try{await fn(signal);}catch(e){if(!signal.aborted)fail(e);}finally{if(!signal.aborted)setBusy(false);}};
  const eligible=eligibility?.methods.find(v=>v.method_id===method),unavailable=eligibility?.unavailable.find(v=>v.method_id===method);
  let parameters:ReturnType<typeof validateMtParameters>|null=null;
  try{if([rho,beta,draws,seed,...(two?[h,basement]:[])].some(v=>!v.trim()))throw new Error("empty parameter");parameters=validateMtParameters({qc_job_id:eligible?.qc_job_id,thickness_m:two?[Number(h)]:[],initial_ohm_m:two?[Number(rho),Number(basement)]:[Number(rho)],beta:Number(beta),bootstrap_samples:Number(draws),seed:Number(seed)});}catch{/* Explicitly disabled below; no guessed values. */}
  const submit=(event:FormEvent)=>{event.preventDefault();if(!receipt)return;setResult(null);setJobId("");setSection("history");void act(async signal=>{const admitted=await clients.mt.submitMt(projectId,receipt,method,method===M05_METHOD?{}:parameters!,signal);if(signal.aborted)return;setJobs(v=>[...v,admitted]);setJobId(admitted.job_id);setNotice(t("Queued admission is not successful computation.","La admisión en cola no es cálculo exitoso."));});};
  const num=(label:string,value:string,set:(v:string)=>void,min:number,max:number,step="any")=><label className="select-control"><span>{label}</span><input className="select" type="number" required min={min} max={max} step={step} value={value} onChange={e=>set(e.target.value)}/></label>;
  const states:Record<ProcessingState,string>={queued:t("Queued","En cola"),running:t("Running","En ejecución"),succeeded:t("Succeeded","Finalizado"),failed:t("Failed","Fallido"),cancelled:t("Cancelled","Cancelado")};
  return <div className="page-body wide workbench processing-workbench mt-workbench">
    <aside className={`instrument-sidebar processing-sidebar ${expanded?"expanded":""}`}><div className="instrument-brand"><span className="small-caps">{t("PRIVATE PROJECT · MT","PROYECTO PRIVADO · MT")}</span><h1>{project?.name??t("MT processing","Procesamiento MT")}</h1></div><div className="processing-actions"><button className="btn" onClick={onGravity}>{t("Gravity station QC","QC de estaciones gravimétricas")}</button><button className="btn" onClick={onManage}>{t("Projects & raw data","Proyectos y datos originales")}</button><button className="btn" onClick={onCurated}>{t("Curated cases","Casos curados")}</button></div>
      <button className="btn mobile-controls-toggle" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{t("MT processing controls","Controles de procesamiento MT")}</button>
      {session==="ready"&&<div className="processing-controls"><label className="select-control"><span>{t("Control section","Sección de controles")}</span><select className="select" value={section} onChange={e=>setSection(e.target.value)}><option value="data">{t("EDI validation","Validación EDI")}</option><option value="run">{t("MT parameters","Parámetros MT")}</option><option value="history">{t("Job history / export","Historial / exportación")}</option></select></label>
        <label className="select-control"><span>{t("Validated EDI dataset","Conjunto EDI validado")}</span><select className="select" value={datasetId} disabled={busy||!receipts.length} onChange={e=>{if(e.target.value!==datasetId){setResult(null);setDataset(null);setDatasetId(e.target.value);}}}>{!receipts.length&&<option value="">{t("No EDI envelope yet","Aún sin envoltura EDI")}</option>}{receipts.map(v=><option key={v.dataset_id} value={v.dataset_id}>{assets.find(a=>a.asset_id===v.raw_asset_id)?.original_filename??v.dataset_id} · {v.row_count} f</option>)}</select></label>
        {section==="data"&&<><label className="select-control"><span>{t("Stored EDI original","Original EDI almacenado")}</span><select className="select" value={assetId} disabled={busy||!assets.length} onChange={e=>setAssetId(e.target.value)}>{!assets.length&&<option value="">{t("No EDI original","Sin original EDI")}</option>}{assets.map(v=><option key={v.asset_id} value={v.asset_id}>{v.original_filename}</option>)}</select></label><p className="project-note">{t("Immutable raw bytes need explicit full tensor, units, frame/rotation, time sign and variance convention. An envelope is not parsed QC. M05 accepts 2–512 frequencies, ≤5 MiB; M06 needs 12–64 and a passing screen.","Bytes inmutables requieren tensor completo, unidades, marco/rotación, signo temporal y convención de varianza explícitos. La envoltura no es QC analizado. M05 admite 2–512 frecuencias, ≤5 MiB; M06 exige 12–64 y filtro aprobado.")}</p><button className="btn primary" disabled={busy||!assetId||receipts.some(v=>v.raw_asset_id===assetId)} onClick={()=>void act(async signal=>{const created=await clients.mt.validateEdi(projectId,assetId,signal);if(signal.aborted)return;setReceipts(v=>[...v,created]);setDatasetId(created.dataset_id);setMethod(M05_METHOD);setSection("run");setNotice(t("Envelope created; full-tensor QC still required.","Envoltura creada; falta QC tensorial completo."));})}>{t("Validate EDI envelope","Validar envoltura EDI")}</button></>}
        {section==="run"&&<form className="processing-run-form" onSubmit={submit}><label className="select-control"><span>{t("MT method","Método MT")}</span><select className="select" value={method} disabled={busy} onChange={e=>setMethod(e.target.value as typeof method)}><option value={M05_METHOD}>{t("M05 · full tensor QC only","M05 · solo QC tensorial completo")}</option><option value={M06_METHOD}>{t("M06 · conditional fixed-thickness TRF","M06 · TRF condicional con espesor fijo")}</option></select></label><p className="project-note" data-testid="mt-eligibility">{eligible?t("API method eligible; host/resources checked at submission.","Método elegible en API; servidor/recursos comprobados al enviar."):unavailable?`${t("Unavailable","No disponible")} · ${unavailable.lane} · ${unavailable.reason}`:t("Read dataset eligibility first.","Lea primero elegibilidad del conjunto.")}</p>
          {method===M06_METHOD&&<><label className="select-control"><span>{t("Imposed geometry","Geometría impuesta")}</span><select className="select" value={two?"two":"halfspace"} onChange={e=>setTwo(e.target.value==="two")}><option value="halfspace">{t("Halfspace (no finite layer)","Semiespacio (sin capa finita)")}</option><option value="two">{t("One finite layer + basement","Una capa finita + basamento")}</option></select></label>{two&&num(t("Fixed thickness h [m]","Espesor fijo h [m]"),h,setH,2,4000)}{num(t("Initial layer resistivity [Ω m]","Resistividad inicial de capa [Ω m]"),rho,setRho,1.000001,5999.999999)}{two&&num(t("Initial basement resistivity [Ω m]","Resistividad inicial de basamento [Ω m]"),basement,setBasement,1.000001,5999.999999)}{num("β [1]",beta,setBeta,0,1)}{num(t("Bootstrap draws [20–40]","Muestras bootstrap [20–40]"),draws,setDraws,20,40,"1")}{num(t("Seed [1]","Semilla [1]"),seed,setSeed,0,2147483647,"1")}<p className="project-note">{t("Fit XY only. All frequencies remain in QC. Holdout is frozen before fitting. Thickness is never inverted; intervals depend on imposed physics and marginal errors.","Ajusta solo XY. Todas las frecuencias permanecen en QC. Reserva congelada antes del ajuste. Nunca invierte espesor; intervalos dependen de física impuesta y errores marginales.")}</p></>}
          <button className="btn primary" disabled={busy||!dataset||!eligible||hasActive||(method===M06_METHOD&&!parameters)}>{t("Submit MT job","Enviar trabajo MT")}</button></form>}
        {section==="history"&&<><label className="select-control"><span>{t("MT job","Trabajo MT")}</span><select className="select" value={jobId} disabled={busy||!history.length} onChange={e=>{if(e.target.value!==jobId){setResult(null);setJobId(e.target.value);}}}>{!history.length&&<option value="">{t("No MT job","Sin trabajo MT")}</option>}{history.map((v,i)=><option key={v.job_id} value={v.job_id}>{i+1} · {v.method_id===M05_METHOD?"M05":"M06"} · {states[v.state]}</option>)}</select></label>{job&&<><p className="project-note">{t("Submitted parameters (immutable)","Parámetros enviados (inmutables)")}: <code>{JSON.stringify(job.request.parameters)}</code></p><button className="btn" disabled={busy||!active(job)||job.cancel_requested} onClick={()=>void act(async signal=>{const updated=await clients.mt.cancel(projectId,job.job_id,signal);if(!signal.aborted)setJobs(v=>v.map(j=>j.job_id===updated.job_id?updated:j));})}>{t(job.cancel_requested?"Cancellation requested":"Cancel MT job",job.cancel_requested?"Cancelación solicitada":"Cancelar trabajo MT")}</button><dl className="processing-limits"><dt>{t("Memory estimate / ceiling","Memoria estimada / límite")}</dt><dd>{job.preflight.estimated_memory_bytes/1048576} / {job.preflight.memory_limit_bytes/1048576} MiB</dd><dt>{t("Scratch / wall ceiling","Límite temporal / duración")}</dt><dd>{job.preflight.scratch_limit_bytes/1048576} MiB / {job.preflight.wall_limit_seconds} s</dd><dt>{t("Measured wall / peak RSS / scratch","Duración / RSS máximo / temporales medidos")}</dt><dd>{job.wall_ms??"—"} ms / {job.peak_rss_bytes===null?"—":(job.peak_rss_bytes/1048576).toFixed(1)} MiB / {job.scratch_bytes??"—"} bytes</dd></dl><button className="btn" disabled={busy||job.state!=="succeeded"||!result} onClick={()=>void act(async signal=>{if(!dataset||!receipt||isFlagJob(job))return;const blob=await clients.mt.mtExport(projectId,job,dataset,receipt,signal);if(signal.aborted)return;const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`mt-${job.job_id}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);setNotice(t("MT member hashes, identities and scientific consistency verified before download; raw bytes excluded.","Hashes, identidades y consistencia científica MT verificados antes de descargar; sin bytes originales."));})}>{t("Verify & export MT ZIP","Verificar y exportar ZIP MT")}</button></>}</>}
        <button className="btn" disabled={busy} onClick={()=>setRevision(v=>v+1)}>{t("Refresh MT project","Actualizar proyecto MT")}</button></div>}
    </aside><section className="instrument-main processing-main" aria-label={t("Selected project MT","MT del proyecto seleccionado")}>
      <div className="processing-status"><strong>{t("M05 QC / M06 conditional candidate","QC M05 / candidato condicional M06")}</strong><span role="status" data-testid="mt-job-status">{job?states[job.state]:t("No job selected","Sin trabajo seleccionado")}</span></div>
      {session!=="ready"?<div className="load-state">{t(session==="checking"?"Checking project ownership…":"Sign in through Projects or retry the unavailable project service.",session==="checking"?"Comprobando titular del proyecto…":"Inicie sesión en Proyectos o reintente el servicio no disponible.")}<button className="btn" onClick={()=>setRevision(v=>v+1)}>{t("Retry MT load","Reintentar carga MT")}</button></div>:result?<MtScientificInstrument key={`${result.dataset_id}:${result.job_id}:${result.request_sha256}`} result={result} es={es}/>:<div className="load-state">{t("Validate an owned EDI original and run M05 to inspect the actual full tensor. No scientific values exist before a successful worker result.","Valide un original EDI propio y ejecute M05 para inspeccionar el tensor real. No existen valores científicos antes de un resultado exitoso del proceso.")}</div>}
      {job?.error&&<p className="project-error" role="alert">{states[job.state]} · {job.error.code}: {job.error.message}</p>}{problem!=null&&<p className="project-error" role="alert">{message(problem)}</p>}{pollError!=null&&<p className="project-error" role="alert">{message(pollError)} <button className="btn" onClick={()=>setPollRetry(v=>v+1)}>{t("Resume MT status check","Reanudar revisión de estado MT")}</button></p>}{notice&&<p role="status" className="project-notice">{notice}</p>}
      <p className="processing-scope">{t("Public MT admission remains closed until the host gate passes. This UI does not activate a service. M05 is QC, M06 is a conditional candidate, neither establishes geological recovery.","Admisión MT pública cerrada hasta aprobar controles del servidor. Esta interfaz no activa el servicio. M05 es QC, M06 es candidato condicional; ninguno establece recuperación geológica.")}</p>
    </section>
  </div>;
}
