import { useState } from "react";
import type { MtFitSummary, MtResult } from "../api/mt-contracts";
import { Plot, LayerColumn, type Series } from "./ScientificPlots";
import { frequencyAxis, mtResidual, partition, quantityUnit, type MtQuantity } from "./mt-view-data";
import { format } from "../science";
import { Cite, Equation, Refs } from "@fasl-work/caos-app-shell";
import { RecordedMtStates } from "./RecordedMtStates";
import { downloadInspection, mtInspection, mtReadout } from "./result-view-data";

export function MtScientificInstrument({result, es}: {result: MtResult; es: boolean}) {
  const t=(en:string,sp:string)=>es?sp:en, s=result.screen, inverse=result.inverse, m=inverse?.methods["mt-lm"];
  const [view,setView]=useState("response"), [quantity,setQuantity]=useState<MtQuantity>("apparent"), [period,setPeriod]=useState(false), [logX,setLogX]=useState(true), [normalized,setNormalized]=useState(true);
  const [pick,setPick]=useState(0), [viewport,setViewport]=useState<[number,number]|null>(null), [layer,setLayer]=useState(0), [milli,setMilli]=useState(false), [axesOpen,setAxesOpen]=useState(false);
  const [errorBars,setErrorBars]=useState(true);
  const errorControl=<label className="project-attestation"><input type="checkbox" checked={errorBars} onChange={e=>setErrorBars(e.target.checked)}/><span>{t("Show marginal SD bars (display only; no QC change)","Mostrar barras de DE marginal (solo visualización; no cambia QC)")}</span></label>;
  const x=frequencyAxis(result.frequency_hz,period), labels=result.frequency_hz.map((_,i)=>inverse?t(inverse.active[i]?"training":"held out",inverse.active[i]?"entrenamiento":"reservada"):t("all-frequency QC","QC de todas las frecuencias"));
  const signedMax=m&&view==="residual"?1.08*Math.max(1e-20,...(["xy","yx"] as const).flatMap(c=>(["real","imag"] as const).flatMap(q=>mtResidual(result,c,q,normalized).map(Math.abs))))*(normalized?1:milli?1000:1):null;
  const plot=(title:string,series:Series[],unit:string, zero=false, extras: {logY?:boolean;fixedYRange?:[number,number]}={})=>{const scale=milli&&unit==="Ω E/H"?1000:1;return <Plot key={title} interactive title={title} x={x} series={series.map(s=>({...s,values:s.values.map(v=>v*scale),errors:s.errors?.map(v=>v*scale)}))} xLabel={period?"T [s]":"f [Hz]"} yLabel={scale===1000?"mΩ E/H":unit} logX={logX} selectedIndex={pick} onSelect={setPick} viewport={viewport} onViewport={setViewport} zeroCentered={zero} fixedYRange={signedMax?[-signedMax,signedMax]:undefined} pointLabels={labels} {...extras}/>;};
  const table=(heads:string[], rows:(string|number)[][],caption?:string)=><div className="processing-station-table"><table className="cmp-table">{caption&&<caption>{caption}</caption>}<thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{typeof v==="number"?format(v):v}</td>)}</tr>)}</tbody></table></div>;
  const comparator=(label:string,v:MtFitSummary): (string|number)[]=>[label,v.model_ohm_m.map(format).join(" / "),v.training_objective,v.training_component_wrms,v.heldout_component_wrms,t(v.solver_success?"success":"failed",v.solver_success?"éxito":"fallo"),v.stop_reason];
  const select=<div className={`processing-station-toolbar mt-toolbar ${axesOpen?"axes-open":""}`}>
    <label className="select-control"><span>{t("Scientific view","Vista científica")}</span><select className="select" value={view} onChange={e=>setView(e.target.value)}><option value="response">{t("XY / −YX response","Respuesta XY / −YX")}</option><option value="tensor">{t("Full tensor & QC","Tensor completo y QC")}</option>{m&&<><option value="residual">{t("Signed complex residuals","Residuos complejos con signo")}</option><option value="model">{t("Fixed-thickness model","Modelo con espesor fijo")}</option><option value="protocol">{t("Holdout & controls","Reserva y controles")}</option><option value="uncertainty">{t("Conditional intervals","Intervalos condicionales")}</option><option value="solver">{t("Solver & local resolution","Solver y resolución local")}</option></>}</select></label>
    <label className="select-control"><span>{t("Selected frequency","Frecuencia seleccionada")}</span><select className="select" value={pick} onChange={e=>setPick(Number(e.target.value))}>{result.frequency_hz.map((f,i)=><option key={i} value={i}>{format(f)} Hz · {format(1/f)} s · {labels[i]}</option>)}</select></label>
    <label className="select-control"><span>{t("Horizontal axis","Eje horizontal")}</span><select className="select" value={period?"period":"frequency"} onChange={e=>{setPeriod(e.target.value==="period");setViewport(null);}}><option value="frequency">f [Hz]</option><option value="period">T [s]</option></select></label>
    <label className="select-control"><span>{t("Horizontal scale","Escala horizontal")}</span><select className="select" value={logX?"log":"linear"} onChange={e=>{setLogX(e.target.value==="log");setViewport(null);}}><option value="log">log₁₀</option><option value="linear">{t("Linear","Lineal")}</option></select></label>
    <label className="select-control"><span>{t("Impedance plot unit","Unidad de impedancia gráfica")}</span><select className="select" value={milli?"milli":"ohm"} onChange={e=>setMilli(e.target.value==="milli")}><option value="ohm">Ω E/H</option><option value="milli">mΩ E/H</option></select></label>
    <button className="btn mt-axis-toggle" aria-expanded={axesOpen} onClick={()=>setAxesOpen(!axesOpen)}>{t("Axis & unit controls","Controles de ejes y unidades")}</button>
  </div>;
  return <div className="processing-instrument mt-instrument" data-testid="mt-instrument">
    <details className="processing-provenance"><summary>{t("Definitions & scientific references","Definiciones y referencias científicas")}</summary><Equation tex={String.raw`\rho_a=\frac{|Z|^2}{\mu_0 2\pi f},\qquad \phi=\operatorname{atan2}(\Im Z,\Re Z),\qquad \mathrm{WRMS}=\sqrt{\frac{1}{2N}\sum_i\left[\left(\frac{\Delta\Re Z_i}{\sigma_i}\right)^2+\left(\frac{\Delta\Im Z_i}{\sigma_i}\right)^2\right]}`} caption={t("E/H impedance, principal phase and marginal-error component WRMS.","Impedancia E/H, fase principal y WRMS por componente con errores marginales.")}/><p>{t("M06 uses bounded SciPy TRF, not an online neural inverse.","M06 utiliza TRF acotado de SciPy, no inversión neuronal en línea.")} <Cite id="scipytrf" paren/></p><Refs ids={["scipytrf","mtpy"]} label={t("References","Referencias")}/></details>
    <div className="evaluation-status" data-evaluation={s.one_d_inversion_eligible?"unresolved":"failed"} data-testid="mt-qc-verdict"><strong>{s.one_d_inversion_eligible?t("Necessary tensor screen passes; 1D geology not established.","Pasa el filtro tensorial necesario; no establece geología 1D."):t("Tensor screen fails: QC only; no 1D inverse.","Falla el filtro tensorial: solo QC; sin inversión 1D.")}</strong><p>{t("Geological truth: null. A successful job is not model recovery.","Verdad geológica: null. Un trabajo exitoso no es recuperación del modelo.")}</p></div>
    {select}
    <output className="processing-station-readout" data-testid="mt-frequency-readout">{result.frequency_hz[pick]} Hz · {1/result.frequency_hz[pick]} s · {labels[pick]} · XY {s.observed.xy.real[pick]} + i {s.observed.xy.imag[pick]} Ω E/H · σ {s.observed.xy.sigma_real_imag_ohm[pick]} Ω / {t("real or imaginary part","parte real o imaginaria")}</output>
    <details className="processing-provenance"><summary>{t("Exact selected response / residual values", "Valores exactos de respuesta / residuo seleccionado")}</summary>
      <div className="processing-station-table" style={{ overflowX: "auto", maxWidth: "100%" }}><table className="cmp-table" data-testid="mt-exact-values" style={{ width: "max-content", minWidth: "100%", tableLayout: "auto" }}><caption>{t("Native E/H ohm; display unit toggles do not change these exact values. -YX is sign-corrected.", "Ohm E/H nativo; cambios de unidad gráfica no alteran estos valores exactos. -YX tiene signo corregido.")}</caption>
        <thead><tr>{[t("Component", "Componente"), "Re Z [Ω E/H]", "Im Z [Ω E/H]", "σ [Ω]", "Re Zpred [Ω E/H]", "Im Zpred [Ω E/H]", "Re ΔZ [Ω E/H]", "Im ΔZ [Ω E/H]", "Re ΔZ/σ [1]", "Im ΔZ/σ [1]"].map(h => <th key={h} style={{ whiteSpace: "nowrap" }}>{h}</th>)}</tr></thead>
        <tbody>{(["xy", "yx"] as const).map(c => { const row = mtReadout(result, pick).components[c]; return <tr key={c}><th>{c === "xy" ? "XY" : "−YX"}</th>{[row.observed.real, row.observed.imag, row.sigma_real_imag_ohm, row.predicted?.real, row.predicted?.imag, row.residual?.real, row.residual?.imag, row.standardized_residual?.real, row.standardized_residual?.imag].map((v, i) => <td key={i} style={{ whiteSpace: "nowrap" }}>{v === undefined ? t("unavailable (QC only)", "no disponible (solo QC)") : String(v)}</td>)}</tr>; })}</tbody>
      </table></div>
      <button className="btn" onClick={() => downloadInspection(mtInspection(result, pick), `mt-inspection-${result.job_id}.json`)}>{t("Export exact inspection JSON", "Exportar inspección exacta JSON")}</button>
    </details>
    {view==="response"&&<>
      {(quantity==="real"||quantity==="imag")&&errorControl}
      <label className="select-control"><span>{t("Response quantity","Magnitud de respuesta")}</span><select className="select" value={quantity} onChange={e=>setQuantity(e.target.value as MtQuantity)}><option value="apparent">ρa [Ω m]</option><option value="phase">φ [°]</option><option value="real">Re Z [Ω E/H]</option><option value="imag">Im Z [Ω E/H]</option></select></label>
      {plot(t("Observed and predicted response","Respuesta observada y predicha"),[
        ...(["xy","yx"] as const).flatMap((c,j)=>inverse?[true,false].map(train=>({name:`${c==="xy"?"XY":"−YX"} · ${t(train?"training":"held out",train?"entrenamiento":"reservada")}`,values:partition(s.observed[c][quantity],inverse.active,train),points:true,errors:errorBars&&(quantity==="real"||quantity==="imag")?s.observed[c].sigma_real_imag_ohm:undefined,color:j?"var(--color-accent-2)":"var(--color-accent)",dashed:!train})): [{name:c==="xy"?"XY":"−YX",values:s.observed[c][quantity],points:true,errors:errorBars&&(quantity==="real"||quantity==="imag")?s.observed[c].sigma_real_imag_ohm:undefined}]),
        ...(m?[{name:t("Selected final prediction (XY fit)","Predicción final seleccionada (ajuste XY)"),values:m.predicted[quantity],color:"var(--color-magenta)"}]:[])],quantityUnit(quantity),false,{logY:quantity==="apparent",fixedYRange:quantity==="phase"?[-180,180]:undefined})}
      <p className="plot-note">{t("Positive exp(+iωt); E/H ohm. −YX is sign-corrected, not an additional fitted component. Error bars are one marginal SD per real/imaginary part; no unprovided rho/phase uncertainty is inferred.","exp(+iωt) positivo; ohm E/H. −YX tiene signo corregido, no es otro componente ajustado. Las barras son una DE marginal por parte real/imaginaria; no se infiere incertidumbre de rho/fase no proporcionada.")}</p>
    </>}
    {view==="tensor"&&<>
      {errorControl}
      {table([t("Criterion","Criterio"),"WRMS [1]",t("Threshold","Umbral"),t("Verdict","Veredicto")],(["xx_component_wrms","yy_component_wrms","antisymmetry_conservative_wrms"] as const).map((k,i)=>[["Zxx / σxx","Zyy / σyy","(Zxy + Zyx) / (σxy + σyx)"][i],s.compatibility[k],3,t(s.compatibility[k]<=3?"passes":"fails",s.compatibility[k]<=3?"pasa":"falla")]))}
      <p className="plot-note">{t("Each score is √(Σ[(Re/σ)²+(Im/σ)²]/(2N)), all original frequencies. The antisymmetry denominator is conservative; marginal errors do not provide tensor covariance. This necessary test cannot establish 1D geology.","Cada puntaje es √(Σ[(Re/σ)²+(Im/σ)²]/(2N)), todas las frecuencias originales. El denominador de antisimetría es conservador; errores marginales no proporcionan covarianza tensorial. Esta prueba necesaria no establece geología 1D.")}</p>
      {plot(t("Per-frequency normalized QC amplitudes","Amplitudes QC normalizadas por frecuencia"),[...[[0,0],[1,1]].map(([a,b],j)=>({name:j?"|Zyy| / (√2 σyy)":"|Zxx| / (√2 σxx)",values:s.tensor.real.map((row,i)=>Math.hypot(row[a][b],s.tensor.imag[i][a][b])/(Math.SQRT2*s.tensor.sigma[i][a][b]))})),{name:"|Zxy + Zyx| / [√2(σxy + σyx)]",values:s.tensor.real.map((row,i)=>Math.hypot(row[0][1]+row[1][0],s.tensor.imag[i][0][1]+s.tensor.imag[i][1][0])/(Math.SQRT2*(s.tensor.sigma[i][0][1]+s.tensor.sigma[i][1][0])))}],"[1]")}
      <p className="plot-note">{t("The RMS of each displayed amplitude over all frequencies equals its pooled QC score. Individual frequencies are not independently accepted/rejected, and this view offers no mask to rescue a failed tensor.","La RMS de cada amplitud mostrada sobre todas las frecuencias es su puntaje QC agregado. No se aceptan/rechazan frecuencias individualmente, y esta vista no ofrece máscara para rescatar un tensor fallido.")}</p>
      <div className="mt-plot-grid">{(["real","imag"] as const).map(q=>plot(q==="real"?"Re Z tensor":"Im Z tensor",[[0,0],[0,1],[1,0],[1,1]].map(([a,b],j)=>({name:["Zxx","Zxy","Zyx","Zyy"][j],values:s.tensor[q].map(row=>row[a][b]),errors:errorBars?s.tensor.sigma.map(row=>row[a][b]):undefined,points:true,color:["var(--color-accent)","var(--color-accent-2)","var(--color-magenta)","var(--color-fg)"][j]})),"Ω E/H",true))}</div>
      {table([t("Component","Componente"),"Re Z [Ω E/H]","Im Z [Ω E/H]","σ [Ω]"],[[0,0],[0,1],[1,0],[1,1]].map(([a,b],j)=>[["Zxx","Zxy","Zyx","Zyy"][j],s.tensor.real[pick][a][b],s.tensor.imag[pick][a][b],s.tensor.sigma[pick][a][b]]))}
      <p>{t("Result frame","Marco resultante")}: {result.physical_metadata.component_frame} · {t("Original / resulting rotation","Rotación original / resultante")}: {s.provenance.original_rotation_deg[pick]} / {s.tensor.rotation_deg[pick]}° · {s.provenance.rotation_action}</p>
      {s.metadata.tipper&&<><p>{t("Ancillary tipper (dimensionless), NOT used in the 1D inverse. Missing frequencies are retained as null.","Tipper auxiliar (adimensional), NO utilizado en la inversión 1D. Frecuencias faltantes conservadas como null.")}</p>{table(["f [Hz]","Re Tx","Im Tx","VAR Tx","Re Ty","Im Ty","VAR Ty"],result.frequency_hz.map((f,i)=>[f,...(["X","Y"] as const).flatMap(c=>[s.metadata.tipper!.components[c].real[i]??"null",s.metadata.tipper!.components[c].imag[i]??"null",s.metadata.tipper!.components[c].variance[i]??"null"])]))}</>}
    </>}
    {view==="residual"&&m&&<><label className="select-control"><span>{t("Residual unit","Unidad residual")}</span><select className="select" value={normalized?"sigma":"ohm"} onChange={e=>setNormalized(e.target.value==="sigma")}><option value="sigma">(Zobs − Zpred) / σ [1]</option><option value="ohm">Zobs − Zpred [Ω E/H]</option></select></label><div className="mt-plot-grid">{(["real","imag"] as const).map(q=>plot(q==="real"?t("Signed real residual","Residuo real con signo"):t("Signed imaginary residual","Residuo imaginario con signo"),(["xy","yx"] as const).flatMap((c,j)=>[true,false].map(train=>({name:`${c==="xy"?"XY":"−YX"} · ${t(train?"training":"held out",train?"entrenamiento":"reservada")}`,values:partition(mtResidual(result,c,q,normalized),inverse!.active,train),points:true,color:j?"var(--color-accent-2)":"var(--color-accent)"}))),normalized?"[1]":"Ω E/H",true))}</div><p>{t("Signed scales are symmetric about zero. −YX residuals test an unfitted component against the XY candidate; they do not imply a second inverse.","Las escalas con signo son simétricas respecto a cero. Los residuos −YX contrastan un componente no ajustado con el candidato XY; no implican segunda inversión.")}</p></>}
    {view==="model"&&m&&inverse&&<>
      <LayerColumn rho={m.model} thickness={inverse.thickness} selectedLayer={layer} onSelect={setLayer} title={t("Selected resistivity profile; imposed thickness","Perfil de resistividad seleccionado; espesor impuesto")}/>
      <output data-testid="mt-layer-readout">{t("Selected layer","Capa seleccionada")} {layer+1} · ρ {m.model[layer]} Ω m · {layer===0?0:inverse.thickness[0]} {t("to","a")} {layer<inverse.thickness.length?inverse.thickness[0]:"∞"} m</output>
      {table([t("Layer","Capa"),t("Top [m]","Techo [m]"),t("Bottom [m]","Base [m]"),"ρ [Ω m]",t("Conditional 2.5–97.5% [Ω m]","Condicional 2,5–97,5% [Ω m]")],m.model.map((v,i)=>[i+1,i===0?0:inverse.thickness[0],i<inverse.thickness.length?inverse.thickness[0]:"∞",v,m.uncertainty.interval_ohm_m?`${m.uncertainty.lower[i]} ${t("to","a")} ${m.uncertainty.upper[i]}`:t("unavailable","no disponible")]))}
      <p>{t("The basement extends to infinity; its displayed height is schematic. Thickness is imposed, not estimated. No lithology or independently known layer truth is assigned.","El basamento se extiende al infinito; su altura mostrada es esquemática. El espesor es impuesto, no estimado. No se asigna litología ni verdad de capas independiente.")}</p>
    </>}
    {view==="protocol"&&m&&inverse&&<>
      <div className="processing-summary" data-testid="mt-fit-metrics"><span>{t("Training WRMS","WRMS entrenamiento")} {m.metrics.active_component_wrms}</span><span>{t("Held-out WRMS","WRMS reservado")} {m.metrics.withheld_component_wrms}</span><span>{t("Unfitted −YX WRMS (all)","WRMS −YX no ajustado (todas)")} {m.metrics.other_component_wrms}</span></div>
      <p>{t("Every fifth sorted frequency is withheld before fitting (index % 5 = 4). Three starts are selected only by training objective. Holdout is not tunable and is from this same sounding, not independent-station validation.","Cada quinta frecuencia ordenada se reserva antes del ajuste (índice % 5 = 4). Tres inicios se seleccionan solo por objetivo de entrenamiento. La reserva no es ajustable y proviene de este sondeo, no valida estaciones independientes.")}</p>
      {table([t("Control","Control"),"ρ [Ω m]","J [1]",t("Train WRMS [1]","WRMS entren. [1]"),t("Holdout WRMS [1]","WRMS reserva [1]"),t("Solver","Solver"),t("Stop receipt (verbatim)","Recibo de parada (literal)")],[...inverse.evaluation_protocol.starts.map(v=>comparator(`${t("Start","Inicio")} ${v.initial_ohm_m.join("/")} Ω m`,v)),comparator(t("Halfspace control","Control semiespacio"),inverse.evaluation_protocol.halfspace_baseline),comparator(`β = ${inverse.evaluation_protocol.beta_sensitivity.beta}`,inverse.evaluation_protocol.beta_sensitivity),...inverse.evaluation_protocol.thickness_sensitivity.map(v=>comparator(`h = ${v.thickness_m.join("/")} m`,v))])}
      <p>{t("Controls contain summaries only; the API provides no comparator response arrays. WRMS = √(Σ[(ΔRe/σ)²+(ΔIm/σ)²]/(2Npartition)). No comparator curves are manufactured.","Los controles contienen solo resúmenes; la API no proporciona respuestas de comparadores. WRMS = √(Σ[(ΔRe/σ)²+(ΔIm/σ)²]/(2Npartición)). No se fabrican curvas de comparadores.")}</p>
      {table(["f [Hz]",t("Partition","Partición")],result.frequency_hz.map((f,i)=>[f,labels[i]]))}
    </>}
    {view==="uncertainty"&&m&&<>
      <p data-testid="mt-bootstrap-status">{t("Conditional bootstrap status","Estado bootstrap condicional")}: {m.uncertainty.status} · {m.uncertainty.completed}/{m.uncertainty.requested} · seed {m.uncertainty.seed}</p>
      <p>{t("Pointwise 95% percentile intervals conditional on selected model, fixed thickness, beta, bounds, source frame, frozen training mask and independent marginal Gaussian errors. Not a geological posterior, simultaneous band or field coverage assertion.","Intervalos percentiles puntuales del 95% condicionados al modelo seleccionado, espesor fijo, beta, límites, marco, máscara de entrenamiento congelada y errores gaussianos marginales independientes. No son posterior geológico, banda simultánea ni afirmación de cobertura de campo.")}</p>
      <label className="select-control"><span>{t("Bootstrap layer","Capa bootstrap")}</span><select className="select" value={layer} onChange={e=>setLayer(Number(e.target.value))}>{m.model.map((_,i)=><option key={i} value={i}>{i+1}</option>)}</select></label>
      <Plot interactive x={m.uncertainty.samples.map((_,i)=>i+1)} series={[{name:t("Successful conditional draw","Muestra condicional exitosa"),values:m.uncertainty.samples.map(row=>row[layer]),points:true}]} title={t("Conditional resistivity samples","Muestras de resistividad condicional")} xLabel={t("successful draw [1]","muestra exitosa [1]")} yLabel="Ω m"/>
      {table([t("Layer","Capa"),"q.025 [Ω m]","q.975 [Ω m]",t("Mean [Ω m]","Media [Ω m]"),"SD [Ω m]"],m.model.map((_,i)=>[i+1,...[m.uncertainty.lower,m.uncertainty.upper,m.uncertainty.mean,m.uncertainty.std].map(v=>v[i]??t("unavailable","no disponible"))]))}
      {table([t("Draw seed","Semilla de muestra"),t("Model [Ω m]","Modelo [Ω m]")],m.uncertainty.successful_seeds.map((seed,i)=>[seed,m.uncertainty.samples[i].join(" / ")]))}
      <h3>{t("Retained failures","Fallos conservados")}</h3>{m.uncertainty.failures.length?table(["seed",t("Error receipt (verbatim)","Recibo de error (literal)")],m.uncertainty.failures.map(v=>[v.seed,v.error])):<p>{t("No failed draws in this receipt.","Sin muestras fallidas en este recibo.")}</p>}
    </>}
    {view==="solver"&&m&&inverse&&<>
      <p>{t("Bounded CPU float64 TRF; residual evaluations are NOT accepted optimizer iterations.","TRF acotado CPU float64; evaluaciones residuales NO son iteraciones aceptadas del optimizador.")}</p>
      {table([t("Receipt","Recibo"),t("Value","Valor")],[["algorithm",m.solver.algorithm],["success / status",`${m.solver.success} / ${m.solver.status}`],["stop (verbatim)",m.solver.stop_reason],["nfev / max_nfev",`${m.solver.nfev} / ${m.solver.max_nfev}`],[t("residual calls","llamadas residuales"),m.solver.residual_calls],["optimality",m.solver.optimality],["ftol / xtol / gtol",Object.values(m.solver.tolerance).join(" / ")],["J data / regularization / total",`${m.objective.data} / ${m.objective.regularization} / ${m.objective.total}`],["β",m.solver.beta],["bounds [Ω m]","1 / 6000"],[t("Local resolution","Resolución local"),m.identifiability.status],[t("Effective / numerical rank","Rango efectivo / numérico"),`${m.identifiability.effective_rank} / ${m.identifiability.numerical_rank} / ${m.identifiability.parameter_count}`],[t("Condition number","Número de condición"),m.identifiability.condition_number??t("undefined (null)","indefinido (null)")]])}
      <RecordedMtStates key={`${result.job_id}:${result.request_sha256}`} result={result} es={es}/>
      {table([t("Layer","Capa"),t("Local log-rho SD","DE local log-rho"),t("Weak direction participation","Participación dirección débil"),t("Near bound","Cerca del límite"),t("Unresolved","No resuelta")],m.model.map((_,i)=>[i+1,m.identifiability.local_logrho_sd[i],m.identifiability.weak_direction_participation[i],String(m.identifiability.near_bound[i]),String(m.identifiability.unresolved_layers.includes(i))]))}
      <p>{t("Local Jacobian diagnostics do not establish global uniqueness. Geological recovery remains unresolved without independent truth.","Diagnósticos locales del Jacobiano no establecen unicidad global. Recuperación geológica no resuelta sin verdad independiente.")}</p>
    </>}
    <details className="processing-provenance"><summary>{t("Source, conventions & exact computation receipts","Fuente, convenciones y recibos exactos de cálculo")}</summary><p>{result.source.provider} · {result.source.attribution} · {result.source.rights_decision} · {result.source.rights_statement}</p>{result.source.exact_url&&<a href={result.source.exact_url} target="_blank" rel="noreferrer">{t("Original source","Fuente original")}</a>}<p>{t("Input unit / time sign / variance","Unidad / signo temporal / varianza originales")}: {s.provenance.original_units} / {s.provenance.original_sign_convention} / {s.provenance.variance_convention}. {t("Unit multiplier to E/H ohm","Multiplicador a ohm E/H")}: {s.provenance.units_multiplier_to_ohm}</p><p>{t("No covariance supplied; no target known. Raw bytes excluded from export.","Sin covarianza proporcionada; sin objetivo conocido. Bytes originales excluidos de exportación.")}</p>{table([t("SHA-256 receipt","Recibo SHA-256"),t("Value","Valor")],[["raw",result.raw_sha256],["dataset",result.dataset_sha256],["request",result.request_sha256],["engine",result.engine_sha256],["parser",result.parser_sha256],["forward",result.forward_sha256],["environment",result.environment_sha256],["M05 screen",result.qc_screen_sha256??"null"]])}<p>Python {result.environment.python} · {Object.entries(result.environment.packages).map(([k,v])=>`${k} ${v}`).join(" · ")}</p></details>
  </div>;
}
