import type { ReactNode } from "react";
import { Callout, Cite, Equation, InlineMath, Refs, SubTabs, useShellLang } from "@fasl-work/caos-app-shell";
import { mtSections, mtArrayRows, type MTMethod, type MTView } from "../data/online-mt-course";
import { OnlineMTDiagram } from "./OnlineMTDiagram";
import { OnlineMTExercise } from "./OnlineMTExercise";
import styles from "./OnlineMTCourse.module.css";

export function OnlineMTCourse({ view, replay }: { view: MTView; replay: ReactNode }) {
  const es = useShellLang() === "es", i = es ? 1 : 0;
  const methods: MTMethod[] = ["m05", "m06"];
  return <div className={styles.course} data-mt-course={view}>
    <p>{es ? "M05 evalúa el tensor EDI completo; M06 ajusta resistividad condicionada por espesor fijo. Curso de la implementación revisada, no afirmación de activación pública ni geología única. Los controles resueltos son replay sintético real." : "M05 screens the complete EDI tensor; M06 fits resistivity conditional on fixed thickness. This is the reviewed implementation's course, not a public-activation or unique-geology assertion. Worked controls are actual synthetic solve replay."} <InlineMath tex={String.raw`\widehat\rho(d;g,\beta,h)`} /> <Cite id="mtonline" paren /></p>
    <SubTabs ariaLabel={es ? "Curso MT por método" : "MT course methods"} tabs={[
      ...methods.map(method => ({ id: method, label: method === "m05" ? "M05 · EDI QC" : es ? "M06 · Inversión 1D" : "M06 · 1D inverse",
        content: <SubTabs ariaLabel={es ? "Temas del curso MT" : "MT course topics"} tabs={mtSections.filter(s => s.method === method && s.view === view).map(section => ({
          id: section.id, label: section.label[i], content: <article className="method-article" data-mt-section={section.id} data-mt-method={method}>
            <h2>{section.title[i]}</h2>
            {section.paragraphs.map((p, index) => <p key={index}>{p.text[i]} <Cite id={p.cite} paren /></p>)}
            {section.equations.map((eq, index) => <Equation key={index} tex={eq.tex} caption={eq.caption[i]} />)}
            <h3>{es ? "Símbolos, funciones y unidades" : "Symbols, functions and units"}</h3>
            <ul className="method-symbols">{section.symbols.map((text, index) => <li key={index}>{text[i]}</li>)}</ul>
            {section.steps && <><h3>{es ? "Algoritmo ejecutado" : "Executed algorithm"}</h3><ol>{section.steps.map((step, index) => <li key={index}>{step[i]}</li>)}</ol></>}
            {section.arrays && <div className={styles.table}><table><caption>{es ? "Arrays del resultado real y funciones creadoras" : "Actual result arrays and creating functions"}</caption><thead><tr>
              {[es ? "Cantidad" : "Quantity", es ? "Forma" : "Shape", es ? "Unidades/ejes" : "Units/axes", es ? "Función" : "Function"].map(label => <th scope="col" key={label}>{label}</th>)}
            </tr></thead><tbody>{mtArrayRows.map(row => <tr key={row.quantity}><th scope="row"><code>{row.quantity}</code></th><td>{row.shape}</td><td>{row.units[i]}</td><td><code>{row.function}</code></td></tr>)}</tbody></table></div>}
            <OnlineMTDiagram method={method} />
            {section.exercise && <OnlineMTExercise method={method} />}
            <Callout variant="honest" title={es ? "Supuestos y límites" : "Assumptions and limits"}>{section.limitation[i]}</Callout>
            <Refs ids={[...new Set(section.paragraphs.map(p => p.cite))]} label={es ? "Referencias" : "References"} />
          </article>,
        }))} />,
      })),
      { id: "replay", label: es ? "Comparadores replay" : "Replay comparators", content: <><p>{es ? "Métodos publicados sobre casos sintéticos: TRF, Adam y parametrización neural por sondeo. No son tres métodos online de EDI." : "Published synthetic-case methods: TRF, Adam and per-sounding neural parameterization. These are not three online EDI methods."}</p>{replay}</> },
    ]} />
  </div>;
}

export function OnlineMTIntroduction() {
  const es = useShellLang() === "es";
  const t = (en: string, sp: string) => es ? sp : en;
  return <div className={styles.course} data-mt-introduction>
    <section>
      <h2>{t("Original data, processing and inversion", "Datos originales, procesamiento e inversión")}</h2>
      <p className="measure">{t("The replacement research platform distinguishes an immutable original from every derived dataset and result. Units, coordinates, epoch, orientation, errors, rights and exact source bytes belong to an owned versioned observation record. A processing run records its parameters and flags or transforms observations without rewriting the original. A physical correction is a specific model of measurement effects and must have its own declared inputs and lineage; it is not interchangeable with an outlier flag or an inverse solve. The currently implemented owner CSV workflow flags gravity-station observations using a submitted threshold and retains their values and sigma. It does not claim a full gravity correction chain or subsurface density recovery.", "La plataforma de reemplazo distingue original inmutable de cada dataset y resultado derivado. Unidades, coordenadas, época, orientación, errores, derechos y bytes exactos pertenecen a registro observado propio versionado. Un procesamiento registra parámetros y marca o transforma observaciones sin reescribir el original. Una corrección física modela efectos de medición con entradas y procedencia declaradas; no se intercambia con flag atípico ni inversión. El flujo CSV propio implementado marca estaciones de gravedad mediante umbral enviado y conserva valores y sigma. No afirma una cadena completa de corrección gravimétrica ni recuperación de densidad del subsuelo.")} <Cite id="processingcontract" paren /></p>
      <Equation tex={String.raw`d^{\rm derived}=T(d^{\rm original};p),\quad \widehat m=\arg\min_m\{\Phi_d(F(m),d^{\rm derived})+\beta\Phi_m(m)\}`} caption={t("T is a declared processing transform, p its parameters; d retains the observation quantity/units or an explicitly declared conversion. F predicts observations from model m. beta weights a model preference. Flag-only processing retains d unchanged and records a separate mask; it is not this inverse minimization.", "T es transformación declarada y p sus parámetros; d conserva cantidad/unidades o conversión explícita. F predice observaciones desde m. beta pondera preferencia de modelo. Procesamiento sólo de flags conserva d y registra máscara separada; no es esta minimización inversa.")} />
      <Refs ids={["processingcontract", "cockett2015"]} label={t("References", "Referencias")} />
    </section>
    <section>
      <h2>{t("EDI compatibility and conditional interpretation", "Compatibilidad EDI e interpretación condicional")}</h2>
      <p className="measure">{t("The reviewed bounded MT vertical is M05 full-tensor EDI QC followed, only for eligible data, by M06 fixed-thickness layered TRF. An owned dataset envelope does not mean the original passed its strict parser or tensor screen. The method requires explicit time sign, native/SI impedance unit, variance meaning and common component frame, and binds M06 to the exact same-source M05 receipt. M05 allows2–512 frequencies; M06 narrows to12–64 and a halfspace or one fixed cover. Clear Lake cl061 remains a measured QC-only exclusion: no1D inverse and no geological truth. Supplied EDI inversion returns truth=null; known targets belong only to explicitly synthetic evaluation.", "La vertical MT acotada revisada es M05 QC EDI de tensor completo y, sólo en datos elegibles, M06 TRF por capas de espesor fijo. Una envolvente propia no significa que el original pase parser estricto ni filtro tensorial. Se exige signo temporal, unidad nativa/SI de impedancia, significado de varianza y marco común, vinculando M06 al mismo recibo fuente M05. M05 admite2–512 frecuencias; M06 limita a12–64 y semiespacio o cubierta fija. Clear Lake cl061 sigue como exclusión medida sólo QC: sin inversión1D ni verdad geológica. EDI suministrado devuelve truth=null; objetivos conocidos sólo pertenecen a evaluación sintética explícita.")} <Cite id="mtcontract" paren /></p>
      <p className="measure">{t("A low residual can coexist with an incorrect thickness, weak parameter sensitivity or a non-1D field response. The MT course derives the complex recurrence and exact weighted objective, demonstrates a wrong-thickness control with a deceptively better frequency holdout, and distinguishes local data-only diagnostics from conditional bootstrap repeatability. It does not treat a passing necessary screen as a dimensionality certificate. The existing synthetic physics lessons below remain useful model experiments, but their known-truth scores cannot be transferred to measured field geology or used as evidence of thirteen online workflows.", "Residuo pequeño puede coexistir con espesor incorrecto, sensibilidad débil o respuesta de campo no1D. El curso deriva recurrencia compleja y objetivo ponderado exacto, muestra h incorrecto con holdout engañosamente mejor y distingue diagnóstico local de datos de repetibilidad bootstrap condicional. Pasar filtro necesario no se trata como certificado dimensional. Las lecciones sintéticas existentes siguen útiles como experimentos, pero scores con verdad conocida no se transfieren a geología de campo ni prueban trece flujos online.")} <Cite id="mtonline" paren /></p>
      <OnlineMTDiagram method="m06" />
      <Refs ids={["mtcontract", "mtonline", "clearlake"]} label={t("References", "Referencias")} />
    </section>
    <section>
      <h2>{t("Bounded CPU, offline GPU and reproducible exchange", "CPU acotada, GPU offline e intercambio reproducible")}</h2>
      <p className="measure">{t("Authenticated owned CSV processing uses the existing private API/worker contract; reviewed EDI jobs add method-specific admission and isolated CPU computation, not static replay on user data. Full waveform inversion, large survey computation and learning/training belong to the offline local CPU/GPU lane; published curated experiments replay audited results, while the MT browser calculator is a separate forward calculation. A queued request is not success. The reviewed MT method remains closed pending accepted actual-host limits, headroom, recovery and security gates. This course asserts neither public API activation nor all M01–M13 methods online, and it does not activate or deploy a second origin.", "Procesamiento CSV propio autenticado usa contrato privado API/worker existente; jobs EDI revisados añaden admisión por método y cálculo CPU aislado, no replay estático de datos de usuario. FWI, grandes levantamientos y aprendizaje/entrenamiento pertenecen a CPU/GPU local offline; experimentos curados publicados reproducen resultados auditados y calculadora MT navegador es cálculo directo separado. Una solicitud en cola no es éxito. MT permanece cerrado pendiente de aceptar límites reales, margen, recuperación y seguridad del host. El curso no afirma API pública activa ni todos M01–M13 online y no activa ni despliega segundo origen.")} <Cite id="mtcontract" paren /></p>
      <p className="measure">{t("Successful processing export carries a compact manifest, dataset and result with original/request/code/environment identities, axes, units, parameters, rights and actual member hashes. Local bundle verification/re-import checks serialized arrays and scientific identities; it does not supply omitted original raw bytes or create redistribution permission. Keep the original source receipt and permitted original separately for independent reprocessing. Offline/GPU results require their own source-valid artifact contracts and integration gates rather than being cast into an online job schema. A verified export, local course build or restricted-host benchmark alone cannot establish field recovery or full product acceptance.", "La exportación exitosa lleva manifest, dataset y result compactos con identidades fuente/solicitud/código/entorno, ejes, unidades, parámetros, derechos y hashes reales. Verificación/reimportación local comprueba arrays e identidades; no aporta bytes originales omitidos ni permiso de redistribución. Conserve recibo y original permitido aparte para reprocesamiento independiente. Resultados offline/GPU requieren contratos y puertas propios, no convertirse a esquema online. Exportación verificada, build local del curso o benchmark restringido no establecen recuperación de campo ni aceptación completa del producto.")} <Cite id="processingcontract" paren /></p>
      <Callout variant="honest" title={t("Execution and acceptance are different", "Ejecución y aceptación son distintas")}>{t("No host activation is asserted. CPU numerical validity, canonical full-family assembly, frontend acceptance and actual-host headroom/security remain independently gated. Field truth stays null.", "No se afirma activación host. Validez numérica CPU, ensamblaje canónico completo, aceptación frontend y margen/seguridad reales tienen puertas independientes. Verdad de campo sigue nula.")}</Callout>
      <Refs ids={["processingcontract", "mtcontract"]} label={t("References", "Referencias")} />
    </section>
  </div>;
}
