import { useEffect, useRef, useState } from "react";
import { readProfileFiles, type ProfileAdmission } from "../api/profile-local-contracts";
import { ProfileLocalInstrument } from "./ProfileLocalInstrument";

export function ProfileLocalWorkbench({es,onCurated}:{es:boolean;onCurated:()=>void}){
  const t=(en:string,sp:string)=>es?sp:en;
  const [resultFile,setResultFile]=useState<File|null>(null),[manifestFile,setManifestFile]=useState<File|null>(null),[admitted,setAdmitted]=useState<ProfileAdmission|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[controls,setControls]=useState(false);
  const epoch=useRef(0);useEffect(()=>()=>{epoch.current++;},[]);
  const choose=(file:File|null,result:boolean)=>{epoch.current++;setBusy(false);setError("");if(result)setResultFile(file);else setManifestFile(file);};
  const open=async()=>{if(!resultFile||!manifestFile)return;const current=++epoch.current;setBusy(true);setError("");try{const value=await readProfileFiles(resultFile,manifestFile);if(epoch.current===current){setAdmitted(value);setControls(false);}}catch{if(epoch.current===current)setError(t("Files rejected. The last admitted result remains; choose matching original result.json and manifest.json.","Archivos rechazados. Se conserva el último resultado admitido; seleccione result.json y manifest.json originales correspondientes."));}finally{if(epoch.current===current)setBusy(false);}};
  return <div className="page-body wide workbench processing-workbench"><aside className={`instrument-sidebar processing-sidebar ${controls?"expanded":""}`}><div className="instrument-brand"><span className="small-caps">{t("LOCAL FILES · NO UPLOAD","ARCHIVOS LOCALES · SIN CARGA")}</span><h1>{t("ERT and traveltime profiles","Perfiles ERT y tiempo de viaje")}</h1></div><button className="btn mobile-controls-toggle" aria-expanded={controls} onClick={()=>setControls(!controls)}>{t("Local profile controls","Controles de perfil local")}</button><div className="processing-controls"><button className="btn" onClick={onCurated}>{t("Curated cases","Casos curados")}</button><label className="select-control"><span>{t("Original result.json","result.json original")}</span><input type="file" accept=".json,application/json" onChange={e=>choose(e.target.files?.[0]??null,true)}/></label><label className="select-control"><span>{t("Matching manifest.json","manifest.json correspondiente")}</span><input type="file" accept=".json,application/json" onChange={e=>choose(e.target.files?.[0]??null,false)}/></label><button className="btn" disabled={busy||!resultFile||!manifestFile} onClick={()=>void open()}>{t("Open local profile result","Abrir resultado de perfil local")}</button>{busy&&<p role="status">{t("Verifying original bytes and native geometry…","Verificando bytes originales y geometría nativa…")}</p>}{error&&<p role="alert">{error}</p>}<p className="plot-note">{t("Run scripts/process_supplied_profile.py with your original and explicit physical metadata first. Files stay in this browser: no account, upload or server computation.","Ejecute primero scripts/process_supplied_profile.py con el original y metadatos físicos explícitos. Los archivos quedan en este navegador: sin cuenta, carga ni cálculo de servidor.")}</p></div></aside><section className="instrument-main processing-main" aria-label={t("Local profile inspection","Inspección local de perfiles")}>{admitted?<ProfileLocalInstrument key={admitted.resultSha256} admitted={admitted} es={es}/>:<p>{t("Choose both files from the same completed local run. No example or substitute result loads automatically.","Seleccione ambos archivos de la misma ejecución local completada. No se carga automáticamente ejemplo ni resultado sustituto.")}</p>}</section></div>;
}
