import { useEffect, useState } from "react";
import { profileSelection, type ProfileAdmission } from "../api/profile-local-contracts";
import { Plot } from "./ScientificPlots";
import { ProfileParameterMesh } from "./ProfileParameterMesh";
import { downloadInspection } from "./result-view-data";

export function ProfileLocalInstrument({admitted,es,lane="local"}:{admitted:ProfileAdmission;es:boolean;lane?:"local"|"protected-worker"}){
  const t=(en:string,sp:string)=>es?sp:en;
  const [fold,setFold]=useState(0),[row,setRow]=useState(0),[cell,setCell]=useState(0),[coverage,setCoverage]=useState(false),[view,setView]=useState("mesh"),[play,setPlay]=useState(false),[low,setLow]=useState(0),[high,setHigh]=useState(0);
  useEffect(()=>{if(!play)return;const id=setInterval(()=>setRow(r=>(r+1)%admitted.rows.length),400);return()=>clearInterval(id);},[play,admitted.rows.length]);
  const model=admitted.models[fold],engine=admitted.result.engine_report as Record<string,unknown>,selected=model?profileSelection(admitted,fold,row,cell):null;
  const source=(admitted.result.metadata as Record<string,unknown>).source as Record<string,unknown>;
  const indices=admitted.rows.map((_,i)=>i),ids=admitted.rows.map((r,i)=>`${i} · ${r.map(v=>v+1).join("/")}`),unit=admitted.method==="ert"?"Ω":"s";
  return <article className="processing-instrument" data-testid="profile-local-instrument" data-state-key={admitted.resultSha256}>
    <details><summary>{admitted.method==="ert"?t("Topographic ERT","ERT topográfica"):t("First-arrival tomography","Tomografía de primeras llegadas")} · {admitted.verdict}</summary>
    <p>{admitted.sourceId} · {t("Returned numerical verdict","Veredicto numérico devuelto")}: {admitted.verdict}</p>
    <p className="plot-note">{t("Original file hashes and scalar consistency checked. No solver replay in this browser; matching hashes are not a signature or proof of field geology. Errors are assumed, not measured covariance.","Hashes originales y coherencia escalar comprobados. Sin reproducción del solver en este navegador; los hashes coincidentes no son firma ni prueba de geología de campo. Los errores son supuestos, no covarianza medida.")}</p>
    </details>
    {model&&selected?<>
      <details><summary>{t("Native row, cell and display controls","Controles nativos de fila, celda y visualización")}</summary>
      <div className="processing-view-controls">
        <label className="select-control"><span>{t("Returned fit","Ajuste devuelto")}</span><select className="select" value={fold} onChange={e=>{setFold(Number(e.target.value));setCell(0);}}>{admitted.models.map((m,i)=><option key={m.name} value={i}>{m.name}</option>)}</select></label>
        <label className="select-control"><span>{t("Map quantity","Magnitud del mapa")}</span><select className="select" value={coverage?"coverage":"model"} onChange={e=>setCoverage(e.target.value==="coverage")}><option value="model">{admitted.method==="ert"?t("Resistivity [Ω m]","Resistividad [Ω m]"):t("Velocity [m/s]","Velocidad [m/s]")}</option><option value="coverage">{t("Coverage, not uncertainty","Cobertura, no incertidumbre")}</option></select></label>
        <label className="select-control"><span>{t("Original measurement row","Fila original de medición")}</span><select className="select" value={row} onChange={e=>setRow(Number(e.target.value))}>{ids.map((id,i)=><option key={i} value={i}>{id}</option>)}</select></label>
        <label className="select-control"><span>{t("Native model cell","Celda nativa del modelo")}</span><input type="number" min={0} max={model.values.length-1} step={1} value={cell} onChange={e=>{const v=Number(e.target.value);if(Number.isInteger(v)&&v>=0&&v<model.values.length)setCell(v);}}/></label>
        <button className="btn" aria-pressed={play} onClick={()=>setPlay(!play)}>{play?t("Pause row playback","Pausar reproducción de filas"):t("Play acquisition rows","Reproducir filas de adquisición")}</button>
      </div>
      <p className="plot-note">{t("Playback moves the linked measurement selection only; it is not wave propagation or unrecorded optimizer history.","La reproducción desplaza solo la selección vinculada de mediciones; no es propagación de ondas ni historia del optimizador no registrada.")}</p>
      <label className="select-control"><span>{t("Acquisition row step","Paso de fila de adquisición")}</span><input type="range" min={0} max={admitted.rows.length-1} step={1} value={row} onChange={e=>setRow(Number(e.target.value))}/></label>
      <output className="processing-station-readout" data-testid="profile-row-readout">{ids[row]} · {selected.row.partition} · {t("observed","observado")} {selected.row.observed} {unit} · {t("predicted","predicho")} {selected.row.predicted} {unit} · Δ {selected.row.residual} {unit} · σ {selected.row.sigma} {unit}</output>
      <output className="processing-station-readout" data-testid="profile-cell-readout">{cell} · [x,z] {selected.cell.centre_m.join(" / ")} m · {selected.cell.value} {selected.cell.unit} · {selected.cell.coverage} {selected.cell.coverage_unit}</output>
      {!coverage&&<div className="processing-view-controls">{[[t("Colour minimum","Mínimo de color"),low,setLow],[t("Colour maximum","Máximo de color"),high,setHigh]].map(([label,value,setter])=><label key={String(label)} className="select-control"><span>{String(label)} [{model.unit}]</span><input type="number" value={value as number} onChange={e=>{const v=Number(e.target.value);if(Number.isFinite(v)&&v>=0)(setter as (v:number)=>void)(v);}}/></label>)}<span>{t("Display only; zero or invalid interval uses the native range.","Solo visualización; cero o intervalo inválido usa el rango nativo.")}</span></div>}
      <label className="select-control"><span>{t("Measurement view","Vista de mediciones")}</span><select className="select" value={view} onChange={e=>setView(e.target.value)}><option value="mesh">{t("Native parameter mesh","Malla nativa de parámetros")}</option><option value="observed">{t("Observed / predicted","Observado / predicho")}</option><option value="residual">{t("Predicted minus observed","Predicho menos observado")}</option><option value="standardized">{t("Residual / assumed sigma","Residual / sigma supuesta")}</option></select></label>
      <button className="btn" onClick={()=>downloadInspection({schema:"geophysics.profile-inspection/v1",execution_lane:lane,physics_replayed:false,result_sha256:admitted.resultSha256,manifest_sha256:admitted.manifestSha256,selected,view,coverage,display_range:[low,high],result:admitted.result},lane==="local"?"local-profile-inspection.json":"profile-inspection.json")}>{lane==="local"?t("Export exact local inspection JSON","Exportar inspección local exacta JSON"):t("Export exact inspection JSON","Exportar inspección exacta JSON")}</button>
      </details>
      {view==="mesh"&&<ProfileParameterMesh model={model} sensors={admitted.sensors} row={admitted.rows[row]} cell={cell} onCell={setCell} coverage={coverage} range={low>0&&high>low?[low,high]:undefined} es={es} provenance={source.kind==="synthetic_control"?"synthetic":"real"}/>}
      {view!=="mesh"&&<>
      <Plot interactive x={indices} selectedIndex={row} onSelect={setRow} pointLabels={ids} title={view==="observed"?t("All observations and frozen prediction","Todas las observaciones y predicción congelada"):view==="residual"?t("Signed residual: predicted − observed","Residual con signo: predicho − observado"):t("Residual / assumed sigma","Residual / sigma supuesta")} xLabel={t("Original measurement index [1]","Índice original de medición [1]")} yLabel={view==="standardized"?"Δ/σ [1]":unit} zeroCentered={view!=="observed"} series={view==="observed"?[{name:t("Observed ± assumed sigma","Observado ± sigma supuesta"),values:model.observed,errors:model.sigma,points:true},{name:t("Frozen prediction","Predicción congelada"),values:model.predicted},{name:t("Held observations","Observaciones reservadas"),values:model.observed.map((v,i)=>model.held.includes(i)?v:NaN),points:true}]:[{name:view==="residual"?"Δ":"Δ/σ",values:view==="residual"?model.residual:model.residual.map((v,i)=>v/model.sigma[i]),points:true}]}/>
      </>}
    </>:<p role="status">{t("No fitted model returned. QC and the original refusal remain available below; no replacement model is drawn.","No se devolvió modelo ajustado. El QC y rechazo original están disponibles abajo; no se dibuja modelo sustituto.")}</p>}
    <details className="processing-provenance"><summary>{t("QC, held-out tests, solver and source","QC, pruebas reservadas, solver y fuente")}</summary><pre>{JSON.stringify({metadata:admitted.result.metadata,original:admitted.result.original,code_hashes:admitted.result.code_hashes,numerical_settings:admitted.result.numerical_settings,qc:engine.qc,inverse_status:engine.inverse_status,inverse_reason:engine.inverse_reason,blocked_validation:engine.blocked_validation,validation_policy:engine.validation_policy,sensitivity:engine.sensitivity,selected_fit:model?.report,engine:engine.engine},null,2)}</pre><p>SHA256 {admitted.resultSha256}</p></details>
  </article>;
}
