import { useState } from "react";
import { velocitySelection, type VelocityAdmission, type VelocityModel } from "../api/velocity-local-contracts";
import { Heatmap, Plot } from "./ScientificPlots";
import { downloadInspection } from "./result-view-data";

type View = "velocity" | "coverage" | "geometry" | "times" | "residual" | "standardized";
export function VelocityLocalInstrument({ admitted, es }: { admitted: VelocityAdmission; es: boolean }) {
  const t = (en: string, sp: string) => es ? sp : en;
  const [model, setModel] = useState<VelocityModel>("classical"), [view, setView] = useState<View>("velocity");
  const [ray, setRay] = useState(0), [x, setX] = useState(0), [z, setZ] = useState(0), [low, setLow] = useState(1400), [high, setHigh] = useState(4000);
  const r = admitted.result, q = r.request, m = r.results[model]!, selected = velocitySelection(r, model, ray, x, z);
  const indices = q.ray_ids.map((_, i) => i), ends = q.rays_m[ray];
  const select = (label: string, value: string | number, change: (v: string) => void, options: [string | number, string][]) => <label className="select-control"><span>{label}</span><select className="select" value={value} onChange={e => change(e.target.value)}>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>;
  return <article data-testid="velocity-local-instrument">
    <h2>{q.id} · {t("Supplied straight-ray result", "Resultado aportado de rayos rectos")}</h2>
    <p className="plot-note">{t("Byte binding and scalar consistency checked; no independent ray-operator or optimizer replay in this browser. A manifest is not a signature. Field truth unknown; field/heldout/online acceptance false.", "Vínculo de bytes y coherencia escalar comprobados; sin reproducción independiente del operador de rayos ni optimizador en este navegador. Un manifiesto no es una firma. Verdad de campo desconocida; aceptación de campo/reserva/en línea falsa.")}</p>
    {r.results.learned && <p role="status" className="sensitivity-warning">{t("NEGATIVE matched CNN benchmark: neither original nor geometry-normalized checkpoint established held-out advantage.", "Ensayo CNN comparado NEGATIVO: ni el checkpoint original ni el normalizado por geometría estableció ventaja en reserva.")} · {r.engine.checkpoint_protocol}</p>}
    <div className="processing-view-controls">
      {select(t("Returned model", "Modelo devuelto"), model, v => setModel(v as VelocityModel), [["classical", t("Classical clipped estimate", "Estimación clásica recortada")], ...(r.results.learned ? [["learned", t("Frozen CNN · negative benchmark", "CNN congelado · ensayo negativo")]] as [string, string][] : [])])}
      {select(t("Local scientific view", "Vista científica local"), view, v => setView(v as View), [["velocity", t("Velocity map", "Mapa de velocidad")], ["coverage", t("Path-length coverage", "Cobertura por longitud de trayecto")], ["geometry", t("Selected ray geometry", "Geometría del rayo seleccionado")], ["times", t("Arrival times", "Tiempos de llegada")], ["residual", t("Signed residuals", "Residuales con signo")], ["standardized", t("Residual / sigma", "Residual / sigma")]])}
      {select(t("Selected ray", "Rayo seleccionado"), ray, v => setRay(Number(v)), q.ray_ids.map((id, i) => [i, id]))}
      {select("x [m]", x, v => setX(Number(v)), r.axes.x_m.map((c, i) => [i, String(c)]))}
      {select(t("Depth [m] · positive down", "Profundidad [m] · positiva hacia abajo"), z, v => setZ(Number(v)), r.axes.depth_m.map((c, i) => [i, String(c)]))}
    </div>
    <output className="processing-station-readout" data-testid="velocity-ray-readout">{selected.ray.id} · [xs,zs,xr,zr] {ends.join(" / ")} m · t {selected.ray.observed_s} s · σ {selected.ray.sigma_s} s · tpred {selected.ray.predicted_s} s · Δt {selected.ray.residual_s} s · Δt/σ {selected.ray.normalized_residual} · tbilinear {selected.ray.bilinear_predicted_s} s</output>
    <output className="processing-station-readout" data-testid="velocity-cell-readout">x {selected.cell.x_m} m · z {selected.cell.depth_m} m · v {selected.cell.velocity_m_s} m/s · {t("coverage", "cobertura")} {selected.cell.coverage_m} m</output>
    {(view === "velocity" || view === "coverage") && <>
      {view === "velocity" && <div className="processing-view-controls">{[[t("Colour minimum [m/s]", "Mínimo de color [m/s]"), low, setLow], [t("Colour maximum [m/s]", "Máximo de color [m/s]"), high, setHigh]].map(([label, value, setter]) => <label className="select-control" key={String(label)}><span>{String(label)}</span><input type="number" value={value as number} onChange={e => { const v = Number(e.target.value); if (Number.isFinite(v) && v > 0) (setter as (n: number) => void)(v); }}/></label>)}<span>{t("Display only; invalid min/max uses the returned range.", "Solo visualización; min/max inválido usa el rango devuelto.")}</span></div>}
      <Heatmap data={view === "velocity" ? m.velocity_m_s : r.coverage_m} title={view === "velocity" ? t("Returned velocity; no known truth", "Velocidad devuelta; sin verdad conocida") : t("Accumulated ray path length; not uncertainty", "Longitud de trayecto acumulada; no incertidumbre")} unit={view === "velocity" ? "m/s" : "m"} palette="velocity" range={view === "velocity" && low < high ? [low, high] : undefined} xLabel="x [m]" yLabel={t("depth [m] · down", "profundidad [m] · abajo")} xRange={[0,800]} yRange={[0,800]} xCoordinates={r.axes.x_m} yCoordinates={r.axes.depth_m} onPick={(cx, cz) => {setX(cx); setZ(cz);}} markers={[{x:ends[0]/800, y:ends[1]/800, label:"S"},{x:ends[2]/800, y:ends[3]/800, label:"R"}]}/>
    </>}
    {view === "geometry" && <Plot interactive x={[ends[0], ends[2]]} series={[{name: selected.ray.id, values:[-ends[1],-ends[3]]}, {name: "S / R", values:[-ends[1],-ends[3]], points:true}]} title={t("Supplied straight segment S→R, not a bent ray", "Segmento recto aportado S→R, no rayo curvo")} xLabel="x [m]" yLabel={t("-depth [m] · up", "-profundidad [m] · arriba")} pointLabels={["S", "R"]}/>}
    {(view === "times" || view === "residual" || view === "standardized") && <Plot interactive x={indices} selectedIndex={ray} onSelect={setRay} pointLabels={q.ray_ids} title={view === "times" ? t("Observed / returned prediction", "Observado / predicción devuelta") : view === "residual" ? t("Observed minus predicted", "Observado menos predicho") : t("Residual divided by declared sigma", "Residual dividido por sigma declarada")} xLabel={t("original ray index [1]", "índice de rayo original [1]")} yLabel={view === "standardized" ? "Δt/σ [1]" : "t [s]"} zeroCentered={view !== "times"} series={view === "times" ? [{name:t("Observed ± sigma", "Observado ± sigma"), values:q.times_s, errors:q.sigma_s, points:true}, {name:t("Cell prediction", "Predicción por celdas"), values:m.predicted_s}, {name:t("Bilinear prediction", "Predicción bilineal"),values:m.bilinear_predicted_s,dashed:true}] : [{name:view === "residual" ? "Δt [s]" : "Δt/σ [1]", values:view === "residual" ? m.residual_s : m.normalized_residual, points:true}]}/>}
    <p className="plot-note">{t("Coverage is path length, not posterior uncertainty. Bilinear comparison is discretization sensitivity, not measured truth. No ray bending, elastic imaging or FWI.", "La cobertura es longitud de trayecto, no incertidumbre posterior. La comparación bilineal es sensibilidad de discretización, no verdad medida. Sin curvatura de rayos, imagen elástica ni FWI.")}</p>
    <p>WRMS {m.data_wrms} · χ² {m.data_chi_square} · {t("cell/bilinear RMSE", "RMSE celdas/bilineal")} {m.cell_vs_bilinear_rmse_s} s · λ {q.lambda}</p>
    <p>{t("Classical: unconstrained Cholesky followed by slowness clipping, not a certified bounded optimum.", "Clásico: Cholesky sin restricciones seguido de recorte de lentitud; no es óptimo acotado certificado.")} · {t("clipped cells", "celdas recortadas")} {r.results.classical.clipped_cells} · {t("regularizer", "regularizador")} {r.results.classical.regularizer}</p>
    <details className="processing-provenance"><summary>{t("Exact provenance and domain limits", "Procedencia exacta y límites de dominio")}</summary><p>{q.source.citation} · {q.source.rights} · {q.source.scope} · {q.frame}</p><pre>{JSON.stringify({source:r.source,engine:r.engine,learned_domain:r.learned_domain,claims:r.claims},null,2)}</pre><ul>{r.warnings.map((w,i) => <li key={i}>{w}</li>)}</ul><p>SHA256 result {admitted.resultSha256} · manifest {admitted.manifestSha256}</p></details>
    <button className="btn" onClick={() => downloadInspection({schema:"geophysics.velocity-inspection/v1", inspection_only:true, physics_replayed:false, result_sha256:admitted.resultSha256, manifest_sha256:admitted.manifestSha256, selected:{...selected,view}, result:r}, "local-velocity-inspection.json")}>{t("Export local exact inspection JSON", "Exportar inspección local exacta JSON")}</button>
  </article>;
}
