import { useEffect, useMemo, useRef, useState } from "react";
import { ApiClient } from "../api/client";
import { LifecycleApi } from "../api/lifecycle";
import type { RawAsset } from "../api/contracts";
import { WaveformApi, WAVEFORM_METHOD, verifyWaveformZip, decodeWaveformArray, type WaveformReceipt, type WaveformDataset, type WaveformJob, type WaveformResult } from "../api/waveform";
import { processingProblem } from "./ProjectProcessingWorkbench";
import type { MethodEligibility } from "../api/processing-contracts";

export function WaveformTrace({x,y,unit,title,cursor,onCursor,axis="t [s]"}:{x:number[];y:number[];unit:string;title:string;cursor:number;onCursor:(value:number)=>void;axis?:string}){
  if(x.length!==y.length||!x.length)return <p>{title} · —</p>;
  let lo=Infinity,hi=-Infinity;for(const v of y){lo=Math.min(lo,v);hi=Math.max(hi,v);}const span=hi-lo||1,x0=x[0],dx=x[x.length-1]-x0||1;
  // Rendering extrema preserves narrow peaks; science and exported arrays are
  // never decimated or altered. Shared cursor is relative to the same time axis.
  const points:string[]=[];const stride=Math.max(1,Math.ceil(y.length/550));
  for(let i=0;i<y.length;i+=stride){let min=i,max=i;for(let j=i;j<Math.min(i+stride,y.length);j++){if(y[j]<y[min])min=j;if(y[j]>y[max])max=j;}for(const j of [...new Set([min,max])].sort((a,b)=>a-b))points.push(`${55+(x[j]-x0)/dx*575},${145-(y[j]-lo)/span*115}`);}
  return <figure className="waveform-trace"><figcaption>{title} · {unit}</figcaption><svg viewBox="0 0 650 180" role="img" aria-label={`${title}; ${axis}; ${unit}`} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();onCursor(x0+Math.max(0,Math.min(1,((e.clientX-r.left)/r.width*650-55)/575))*dx);}}>
    <path d="M55 25V145H630" fill="none" stroke="currentColor"/><polyline points={points.join(" ")} fill="none" stroke="var(--accent)" strokeWidth="1.2"/>
    {cursor>=x0&&cursor<=x0+dx&&<path d={`M${55+(cursor-x0)/dx*575} 25V145`} stroke="currentColor" strokeDasharray="3 3"/>}
    <text x="4" y="33" fontSize="11" fill="currentColor">{hi.toPrecision(3)}</text><text x="4" y="145" fontSize="11" fill="currentColor">{lo.toPrecision(3)}</text><text x="55" y="166" fontSize="11" fill="currentColor">{x0.toPrecision(3)}</text><text x="595" y="166" fontSize="11" fill="currentColor">{(x0+dx).toPrecision(3)}</text><text x="295" y="174" fontSize="12" fill="currentColor">{axis}</text>
  </svg></figure>;
}

export function WaveformProjectWorkbench({projectId,es,onManage,onCurated}:{projectId:string;es:boolean;onManage:()=>void;onCurated:()=>void}){
  const t=(en:string,sp:string)=>es?sp:en;
  const clients=useMemo(()=>{const api=new ApiClient(typeof window==="undefined"?"http://127.0.0.1":window.location.origin);return {wave:new WaveformApi(api),life:new LifecycleApi(api)};},[]);
  const [assets,setAssets]=useState<RawAsset[]>([]),[receipts,setReceipts]=useState<WaveformReceipt[]>([]),[jobs,setJobs]=useState<WaveformJob[]>([]);
  const [datasetId,setDatasetId]=useState(""),[assetId,setAssetId]=useState(""),[jobId,setJobId]=useState(""),[request,setRequest]=useState("");
  const [dataset,setDataset]=useState<WaveformDataset|null>(null),[methods,setMethods]=useState<MethodEligibility|null>(null),[result,setResult]=useState<WaveformResult|null>(null),[files,setFiles]=useState<Record<string,Uint8Array>|null>(null);
  const [controlsOpen,setControlsOpen]=useState(false),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(""),[revision,setRevision]=useState(0),[channel,setChannel]=useState(0),[cursor,setCursor]=useState(0);
  const action=useRef<AbortController|null>(null);
  const receipt=receipts.find(r=>r.dataset_id===datasetId),history=jobs.filter(j=>j.dataset_id===datasetId),job=history.find(j=>j.job_id===jobId);
  const active=jobs.some(j=>["queued","running"].includes(j.state));
  useEffect(()=>{const c=new AbortController();setReady(false);setError("");setAssets([]);setReceipts([]);setJobs([]);setDataset(null);setMethods(null);setResult(null);setFiles(null);
    void (async()=>{const session=await clients.life.session(c.signal);if(!session.account)throw new Error(t("Sign in through Projects to load private data.","Inicie sesión en Proyectos para cargar datos privados."));if(!(await clients.life.projects(c.signal)).some(p=>p.id===projectId))throw new Error("Owned project not found");const [raw,rows,history]=await Promise.all([clients.life.assets(projectId,c.signal),clients.wave.datasets(projectId,c.signal),clients.wave.jobs(projectId,c.signal)]);if(c.signal.aborted)return;setAssets(raw.filter(a=>a.detected_format==="miniseed"));setReceipts(rows.filter((r):r is WaveformReceipt=>r.modality==="waveform_counts_response"));setJobs(history.filter((j):j is WaveformJob=>j.method_id===WAVEFORM_METHOD));setReady(true);})().catch(e=>{if(!c.signal.aborted)setError(processingProblem(e,es));});return()=>{c.abort();action.current?.abort();};
  },[clients,projectId,es,revision]);
  useEffect(()=>{setDataset(null);setMethods(null);setResult(null);setFiles(null);if(!ready||!receipt)return;const c=new AbortController();void Promise.all([clients.wave.waveformDataset(projectId,receipt,c.signal),clients.wave.methods(projectId,receipt.dataset_id,c.signal)]).then(([d,m])=>{if(!c.signal.aborted){setDataset(d);setMethods(m);}}).catch(e=>{if(!c.signal.aborted)setError(processingProblem(e,es));});return()=>c.abort();},[clients,projectId,ready,receipt,es]);
  useEffect(()=>{if(!ready||!active)return;const c=new AbortController();const timer=setInterval(()=>{void clients.wave.jobs(projectId,c.signal).then(rows=>{if(!c.signal.aborted)setJobs(rows.filter((j):j is WaveformJob=>j.method_id===WAVEFORM_METHOD));}).catch(e=>{if(!c.signal.aborted)setError(processingProblem(e,es));});},1000);return()=>{c.abort();clearInterval(timer);};},[clients,projectId,ready,active,es]);
  useEffect(()=>{setResult(null);setFiles(null);if(!dataset||!job||job.state!=="succeeded")return;const c=new AbortController();void clients.wave.waveformResult(projectId,job,dataset,c.signal).then(r=>{if(!c.signal.aborted)setResult(r);}).catch(e=>{if(!c.signal.aborted)setError(processingProblem(e,es));});return()=>c.abort();},[clients,projectId,dataset,job,es]);
  async function act(fn:(signal:AbortSignal)=>Promise<void>){action.current?.abort();const c=new AbortController();action.current=c;setBusy(true);setError("");try{await fn(c.signal);}catch(e){if(!c.signal.aborted)setError(processingProblem(e,es));}finally{if(!c.signal.aborted)setBusy(false);}}
  const stateLabel=(state:WaveformJob["state"])=>({queued:t("Queued","En cola"),running:t("Running","En ejecución"),succeeded:t("Succeeded","Finalizado"),failed:t("Failed","Fallido"),cancelled:t("Cancelled","Cancelado")})[state];
  const enabled=methods?.methods.some(m=>m.method_id===WAVEFORM_METHOD)??false;
  const descriptors=result?.calculation.array_descriptors.filter(d=>d.channel_index===channel)??[];
  const arrays=useMemo(()=>{const values:Record<string,number[]>={};if(files)for(const d of descriptors)values[d.name]=decodeWaveformArray(files[`c0${d.channel_index}-${d.name}.bin`],d);return values;},[files,result,channel]);
  const channelMetadata=result?.calculation.channels[channel];
  function xFor(name:string,values:number[]){if(name.endsWith("psd"))return arrays.psd_frequency_hz??[];const rate=channelMetadata?.sample_rate_hz??1;const start=name==="counts"&&dataset?(Number(channelMetadata?.start_us)/1e6-Date.parse(String(dataset.request.conditioning_start_utc))/1000):0;return values.map((_,i)=>start+i/rate);}
  return <div className="page-body wide workbench processing-workbench" data-testid="waveform-project"><aside className={`instrument-sidebar processing-sidebar ${controlsOpen?"expanded":""}`}>
    <h1>{t("Own waveform processing","Procesamiento de ondas propias")}</h1><p>{t("MiniSEED + exact owned StationXML. Structural indexing is not physical QC.","MiniSEED + StationXML propio exacto. El índice estructural no es QC físico.")}</p>
    <button className="btn" onClick={onManage}>{t("Projects · upload originals","Proyectos · cargar originales")}</button><button className="btn" onClick={onCurated}>{t("Curated cases","Casos curados")}</button>
    <button className="btn mobile-controls-toggle" aria-expanded={controlsOpen} onClick={()=>setControlsOpen(!controlsOpen)}>{t("Processing controls","Controles de procesamiento")}</button><div className="processing-controls">
    {error&&<p role="alert" className="project-error">{error}</p>}
    <label>{t("Stored MiniSEED","MiniSEED almacenado")}<select value={assetId} disabled={!ready||busy} onChange={e=>setAssetId(e.target.value)}><option value="">—</option>{assets.map(a=><option key={a.asset_id} value={a.asset_id}>{a.original_filename}</option>)}</select></label>
    <label>{t("Explicit scientific request JSON","Solicitud científica JSON explícita")}<textarea aria-label={t("Scientific request JSON","Solicitud científica JSON")} value={request} onChange={e=>setRequest(e.target.value)} rows={10} maxLength={65536}/></label>
    <label>{t("Load request file","Cargar archivo de solicitud")}<input type="file" accept=".json,application/json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void act(async()=>{if(file.size>65536)throw new Error(t("Request exceeds 64 KiB","Solicitud supera 64 KiB"));setRequest(await file.text());});}}/></label>
    <button className="btn" disabled={!ready||busy||!assetId||!request.trim()} onClick={()=>void act(async signal=>{const r=await clients.wave.index(projectId,assetId,JSON.parse(request),signal);if(signal.aborted)return;setReceipts(rows=>[...rows,r]);setDatasetId(r.dataset_id);setJobId("");})}>{t("Index exact pair and request","Indexar par y solicitud exactos")}</button>
    <label>{t("Immutable dataset","Conjunto inmutable")}<select value={datasetId} disabled={busy} onChange={e=>{setDatasetId(e.target.value);setJobId("");}}><option value="">—</option>{receipts.map(r=><option key={r.dataset_id} value={r.dataset_id}>{r.dataset_id.slice(0,8)} · {r.row_count} {t("samples","muestras")}</option>)}</select></label>
    {methods?.unavailable.map(m=><p key={m.method_id} role="status">{m.reason}</p>)}
    <button className="btn" disabled={!dataset||!receipt||!enabled||active||busy} onClick={()=>void act(async signal=>{if(!receipt||!dataset)return;const j=await clients.wave.submitWaveform(projectId,receipt,dataset,signal);if(signal.aborted)return;setJobs(rows=>[...rows,j]);setJobId(j.job_id);})}>{t("Run full processing","Ejecutar procesamiento completo")}</button>
    <label>{t("Job history","Historial de trabajos")}<select value={jobId} onChange={e=>setJobId(e.target.value)}><option value="">—</option>{history.map(j=><option key={j.job_id} value={j.job_id}>{j.job_id.slice(0,8)} · {stateLabel(j.state)}</option>)}</select></label>
    {job&&<><p role="status">{stateLabel(job.state)} {job.error?.code}</p><button className="btn" disabled={busy||!["queued","running"].includes(job.state)||job.cancel_requested} onClick={()=>void act(async signal=>{const j=await clients.wave.cancel(projectId,job.job_id,signal);if(!signal.aborted&&j.method_id===WAVEFORM_METHOD)setJobs(rows=>rows.map(row=>row.job_id===j.job_id?j:row));})}>{t("Cancel job","Cancelar trabajo")}</button><details><summary>{t("Submitted parameters and limits","Parámetros enviados y límites")}</summary><pre>{JSON.stringify(job.request.scientific_request,null,2)}</pre><p>{job.preflight.memory_limit_bytes/1048576} MiB · {job.preflight.scratch_limit_bytes} bytes · {job.preflight.wall_limit_seconds} s</p></details></>}
    <button className="btn" disabled={busy} onClick={()=>setRevision(v=>v+1)}>{t("Reload project","Recargar proyecto")}</button>
  </div></aside><section className="instrument-main processing-main"><h2>M08 · {t("QC, response, filter, PSD and unlabelled arrivals","QC, respuesta, filtro, PSD y llegadas sin etiquetas")}</h2>
    {result&&job&&<><p>{result.scientific_status} · {result.calculation.qc.reasons.join(", ")}</p><p>{t("Job committed-memory peak, not RSS","Memoria comprometida máxima, no RSS")}: {(result.resources.peak_memory_bytes/1048576).toFixed(1)} MiB · CPU {(result.resources.cpu_ns/1e9).toFixed(3)} s</p>
      <button className="btn" disabled={busy} onClick={()=>void act(async signal=>{const blob=await clients.wave.waveformExport(projectId,job,result,signal);const decoded=await verifyWaveformZip(blob,result);if(signal.aborted)return;setFiles(decoded);const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`waveform-${job.job_id}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);})}>{t("Verify, plot and export all arrays","Verificar, graficar y exportar todas las matrices")}</button>
      <label>{t("Reopen saved ZIP against this successful job","Reabrir ZIP guardado contra este trabajo exitoso")}<input type="file" accept=".zip,application/zip" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void act(async signal=>{const decoded=await verifyWaveformZip(f,result);if(!signal.aborted)setFiles(decoded);});}}/></label>
      <label>{t("Measured channel","Canal medido")}<select value={channel} onChange={e=>setChannel(Number(e.target.value))}>{result.calculation.channels.map((_,i)=><option key={i} value={i}>c0{i} · {String((dataset?.request.channels as {channel:string}[]|undefined)?.[i]?.channel??"")}</option>)}</select></label>
      <p>{t("Shared time cursor relative to conditioning start","Cursor temporal compartido desde inicio de acondicionamiento")}: {cursor.toFixed(3)} s</p>
      {files&&descriptors.filter(d=>["counts","physical_native","filtered_native","characteristic","counts_psd","physical_psd","filtered_psd"].includes(d.name)).map(d=><WaveformTrace key={d.name} x={xFor(d.name,arrays[d.name])} y={arrays[d.name]} unit={d.unit} title={d.name} axis={d.name.endsWith("psd")?"f [Hz]":"t [s]"} cursor={d.name.endsWith("psd")?-1:cursor} onCursor={d.name.endsWith("psd")?()=>{}:setCursor}/>)}
      <details><summary>{t("QC, edge masks, response and pick provenance","QC, máscaras de borde, respuesta y procedencia de llegadas")}</summary><pre>{JSON.stringify(result.calculation,null,2)}</pre></details>
    </>}
    <p>{t("No P/S reassignment, catalogue tuning or invented uncertainty. Offline zero-phase filtering is acausal. These results do not establish subsurface truth or host acceptance.","Sin reasignación P/S, ajuste al catálogo ni incertidumbre inventada. El filtro offline de fase cero es acausal. Estos resultados no establecen verdad del subsuelo ni aceptación del host.")}</p>
  </section></div>;
}
