import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { ApiClient, ApiHttpError } from "../api/client";
import { LifecycleApi } from "../api/lifecycle";
import type { RawAsset } from "../api/contracts";
import { WaveformApi, WAVEFORM_METHOD, verifyWaveformZip, decodeWaveformArray, type WaveformReceipt, type WaveformDataset, type WaveformJob, type WaveformResult } from "../api/waveform";
import { processingProblem } from "./ProjectProcessingWorkbench";
import type { MethodEligibility } from "../api/processing-contracts";
import { readProtectedWaveform,waveformResultBytes,WAVEFORM_RESULT_BYTE_CAP } from "../api/waveform-linux-receipt";
import { WaveformRequestControls } from "./WaveformRequestControls";
import { draftIssues, requestBinding, responseDisplay, waveformUtcUs } from "./waveform-request";
import { WorkbenchLayout, type RailSection } from "@fasl-work/caos-app-shell";

export function WaveformTrace({x,y,unit,title,cursor,onCursor,axis="t [s]",markers=[]}:{x:number[];y:number[];unit:string;title:string;cursor:number;onCursor:(value:number)=>void;axis?:string;markers?:{value:number;title:string}[]}){
  const svg=useRef<SVGSVGElement|null>(null),[size,setSize]=useState({width:650,height:310});
  useEffect(()=>{const element=svg.current;if(!element)return;const measure=()=>{const box=element.getBoundingClientRect();const next={width:Math.max(280,box.width),height:Math.max(220,box.height)};setSize(old=>old.width===next.width&&old.height===next.height?old:next);};measure();const observer=new ResizeObserver(measure);observer.observe(element);return()=>observer.disconnect();},[x.length,y.length]);
  if(x.length!==y.length||!x.length)return <p>{title} · -</p>;
  let lo=Infinity,hi=-Infinity;for(const v of y){lo=Math.min(lo,v);hi=Math.max(hi,v);}const span=hi-lo||1,x0=x[0],dx=x[x.length-1]-x0||1;
  const left=64,right=size.width-20,top=24,bottom=size.height-44,plotWidth=right-left,plotHeight=bottom-top;
  // Rendering extrema preserves narrow peaks; science and exported arrays are
  // never decimated or altered. Shared cursor is relative to the same time axis.
  const points:string[]=[];const stride=Math.max(1,Math.ceil(y.length/Math.floor(plotWidth)));
  for(let i=0;i<y.length;i+=stride){let min=i,max=i;for(let j=i;j<Math.min(i+stride,y.length);j++){if(y[j]<y[min])min=j;if(y[j]>y[max])max=j;}for(const j of [...new Set([min,max])].sort((a,b)=>a-b))points.push(`${left+(x[j]-x0)/dx*plotWidth},${bottom-(y[j]-lo)/span*plotHeight}`);}
  return <figure className="waveform-trace processing-plot"><figcaption>{title} · {unit}</figcaption><svg ref={svg} viewBox={`0 0 ${size.width} ${size.height}`} role="img" tabIndex={0} aria-label={`${title}; ${axis}; ${unit}`} onKeyDown={e=>{let next=cursor;const step=x.length>1?dx/(x.length-1):1;if(e.key==="ArrowLeft")next-=step;else if(e.key==="ArrowRight")next+=step;else if(e.key==="Home")next=x0;else if(e.key==="End")next=x0+dx;else return;e.preventDefault();onCursor(Math.max(x0,Math.min(x0+dx,next)));}} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();onCursor(x0+Math.max(0,Math.min(1,((e.clientX-r.left)/r.width*size.width-left)/plotWidth))*dx);}}>
    <path d={`M${left} ${top}V${bottom}H${right}`} fill="none" stroke="currentColor"/><polyline points={points.join(" ")} fill="none" stroke="var(--color-accent)" strokeWidth="1.2"/>
    {cursor>=x0&&cursor<=x0+dx&&<path d={`M${left+(cursor-x0)/dx*plotWidth} ${top}V${bottom}`} stroke="currentColor" strokeDasharray="3 3"/>}
    {markers.filter(m=>Number.isFinite(m.value)&&m.value>=x0&&m.value<=x0+dx).map((m,i)=><path key={i} d={`M${left+(m.value-x0)/dx*plotWidth} ${top}V${bottom}`} stroke="currentColor" strokeDasharray="6 4"><title>{m.title}</title></path>)}
    <text x="4" y={top+9} fill="currentColor">{hi.toPrecision(3)}</text><text x="4" y={bottom} fill="currentColor">{lo.toPrecision(3)}</text><text x={left} y={bottom+20} fill="currentColor">{x0.toPrecision(3)}</text><text x={right} y={bottom+20} textAnchor="end" fill="currentColor">{(x0+dx).toPrecision(3)}</text><text x={(left+right)/2} y={size.height-5} textAnchor="middle" fill="currentColor">{axis}</text>
  </svg></figure>;
}

type WaveformWorkbenchProps={projectId:string;es:boolean;onManage:()=>void;onCurated:()=>void;methodNavigation?:ReactNode};
export function WaveformProjectWorkbench(props:WaveformWorkbenchProps){
  // Enforce project custody even when the caller does not supply a React key.
  return <OwnedWaveformWorkbench key={props.projectId} {...props}/>;
}
function OwnedWaveformWorkbench({projectId,es,onManage,onCurated,methodNavigation}:WaveformWorkbenchProps){
  const t=(en:string,sp:string)=>es?sp:en;
  const clients=useMemo(()=>{const api=new ApiClient(typeof window==="undefined"?"http://127.0.0.1":window.location.origin);return {wave:new WaveformApi(api),life:new LifecycleApi(api)};},[]);
  const [assets,setAssets]=useState<RawAsset[]>([]),[receipts,setReceipts]=useState<WaveformReceipt[]>([]),[jobs,setJobs]=useState<WaveformJob[]>([]);
  const [datasetId,setDatasetId]=useState(""),[assetId,setAssetId]=useState(""),[jobId,setJobId]=useState(""),[request,setRequest]=useState("");
  const [reviewedBinding,setReviewedBinding]=useState("");
  const [dataset,setDataset]=useState<WaveformDataset|null>(null),[methods,setMethods]=useState<MethodEligibility|null>(null),[result,setResult]=useState<WaveformResult|null>(null),[files,setFiles]=useState<Record<string,Uint8Array>|null>(null);
  const [busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(""),[revision,setRevision]=useState(0),[channel,setChannel]=useState(0),[cursor,setCursor]=useState(0);
  const action=useRef<AbortController|null>(null);
  const pending=useRef(new Set<AbortController>());
  const downloads=useRef(new Set<string>());
  function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement("a");downloads.current.add(url);a.href=url;a.download=name;a.click();setTimeout(()=>{URL.revokeObjectURL(url);downloads.current.delete(url);},30000);}
  function controller(){const c=new AbortController();pending.current.add(c);return c;}
  function invalidate(){for(const c of pending.current)c.abort();pending.current.clear();action.current?.abort();action.current=null;for(const url of downloads.current)URL.revokeObjectURL(url);downloads.current.clear();}
  function clearPrivate(){invalidate();setReady(false);setBusy(false);setAssets([]);setReceipts([]);setJobs([]);setAssetId("");setDatasetId("");setJobId("");setRequest("");setReviewedBinding("");setDataset(null);setMethods(null);setResult(null);setFiles(null);setChannel(0);setCursor(0);}
  function problem(e:unknown){if(e instanceof ApiHttpError&&e.status===401)clearPrivate();setError(processingProblem(e,es));}
  function forgetSource(){clearPrivate();setError("");setRevision(v=>v+1);}
  useEffect(()=>()=>invalidate(),[]);
  const receipt=receipts.find(r=>r.dataset_id===datasetId),history=jobs.filter(j=>j.dataset_id===datasetId),job=history.find(j=>j.job_id===jobId);
  const asset=assets.find(a=>a.asset_id===assetId),companion=assets.find(a=>a.asset_id===asset?.physical_metadata.geometry.stationxml_asset_id);
  const binding=requestBinding(asset,request),requestErrors=draftIssues(request);
  useEffect(()=>{setChannel(0);setCursor(0);},[datasetId,jobId]);
  const active=jobs.some(j=>["queued","running"].includes(j.state));
  useEffect(()=>{const c=controller();setReady(false);setError("");setAssets([]);setReceipts([]);setJobs([]);setDataset(null);setMethods(null);setResult(null);setFiles(null);
    void (async()=>{const session=await clients.life.session(c.signal);if(!session.account)throw new ApiHttpError(401,"session_expired",t("Sign in through Projects to load private data.","Inicie sesión en Proyectos para cargar datos privados."));if(!(await clients.life.projects(c.signal)).some(p=>p.id===projectId))throw new Error("Owned project not found");const [raw,rows,history]=await Promise.all([clients.life.assets(projectId,c.signal),clients.wave.datasets(projectId,c.signal),clients.wave.jobs(projectId,c.signal)]);if(c.signal.aborted)return;setAssets(raw);setReceipts(rows.filter((r):r is WaveformReceipt=>r.modality==="waveform_counts_response"));setJobs(history.filter((j):j is WaveformJob=>j.method_id===WAVEFORM_METHOD));setReady(true);})().catch(e=>{if(!c.signal.aborted)problem(e);});return()=>{c.abort();pending.current.delete(c);action.current?.abort();};
  },[clients,projectId,es,revision]);
  useEffect(()=>{setDataset(null);setMethods(null);setResult(null);setFiles(null);if(!ready||!receipt)return;const c=controller();void Promise.all([clients.wave.waveformDataset(projectId,receipt,c.signal),clients.wave.methods(projectId,receipt.dataset_id,c.signal)]).then(([d,m])=>{if(!c.signal.aborted){setDataset(d);setMethods(m);}}).catch(e=>{if(!c.signal.aborted)problem(e);});return()=>{c.abort();pending.current.delete(c);};},[clients,projectId,ready,receipt,es]);
  useEffect(()=>{if(!ready||!active)return;const c=controller();const timer=setInterval(()=>{void clients.wave.jobs(projectId,c.signal).then(rows=>{if(!c.signal.aborted)setJobs(rows.filter((j):j is WaveformJob=>j.method_id===WAVEFORM_METHOD));}).catch(e=>{if(!c.signal.aborted)problem(e);});},1000);return()=>{c.abort();pending.current.delete(c);clearInterval(timer);};},[clients,projectId,ready,active,es]);
  useEffect(()=>{setResult(null);setFiles(null);if(!dataset||!job||job.state!=="succeeded")return;const c=controller();void clients.wave.waveformResult(projectId,job,dataset,c.signal).then(r=>{if(!c.signal.aborted)setResult(r);}).catch(e=>{if(!c.signal.aborted)problem(e);});return()=>{c.abort();pending.current.delete(c);};},[clients,projectId,dataset,job,es]);
  async function act(fn:(signal:AbortSignal)=>Promise<void>){action.current?.abort();const c=controller();action.current=c;setBusy(true);setError("");try{await fn(c.signal);}catch(e){if(!c.signal.aborted)problem(e);}finally{pending.current.delete(c);if(!c.signal.aborted)setBusy(false);}}
  const stateLabel=(state:WaveformJob["state"])=>({queued:t("Queued","En cola"),running:t("Running","En ejecución"),succeeded:t("Succeeded","Finalizado"),failed:t("Failed","Fallido"),cancelled:t("Cancelled","Cancelado")})[state];
  const enabled=methods?.methods.some(m=>m.method_id===WAVEFORM_METHOD)??false;
  const descriptors=result?.calculation.array_descriptors.filter(d=>d.channel_index===channel)??[];
  const arrays=useMemo(()=>{const values:Record<string,number[]>={};if(files)for(const d of descriptors)values[d.name]=decodeWaveformArray(files[`c0${d.channel_index}-${d.name}.bin`],d);return values;},[files,result,channel]);
  const channelMetadata=result?.calculation.channels[channel];
  const response=useMemo(()=>{try{return {curves:responseDisplay(arrays,descriptors),error:false};}catch{return {curves:null,error:true};}},[files,result,channel]);
  const conditioningUs=dataset?waveformUtcUs(dataset.request.conditioning_start_utc):NaN;
  const markers=dataset?[{value:(waveformUtcUs(dataset.request.analysis_start_utc)-conditioningUs)/1e6,title:t("Analysis start","Inicio de análisis")},{value:(waveformUtcUs(dataset.request.analysis_end_utc)-conditioningUs)/1e6,title:t("Analysis end (exclusive)","Fin de análisis (exclusivo)")}]:[];
  function xFor(name:string,values:number[]){if(name.endsWith("psd"))return arrays.psd_frequency_hz??[];if(name==="prefilter_weight")return arrays.response_frequency_hz??[];const rate=channelMetadata!.sample_rate_hz;const start=name==="counts"?(channelMetadata!.start_us-conditioningUs)/1e6:0;return values.map((_,i)=>start+i/rate);}
  // Resolve shared BiText labels from the instrument's explicit language prop,
  // just like its controls, including a server render before store hydration.
  const sections:RailSection[]=[{id:"source",label:t("Source / index","Fuente / índice"),content:<div className="processing-controls">
    <label className="select-control">{t("Stored MiniSEED","MiniSEED almacenado")}<select className="select" value={assetId} disabled={!ready||busy} onChange={e=>{if(!e.target.value){forgetSource();return;}setAssetId(e.target.value);setReviewedBinding("");}}><option value="">{t("Select original","Seleccionar original")}</option>{assets.filter(a=>a.detected_format==="miniseed").map(a=><option key={a.asset_id} value={a.asset_id}>{a.original_filename}</option>)}</select></label>
    <button className="btn" onClick={forgetSource}>{t("Forget source and private draft","Olvidar fuente y borrador privado")}</button>
    {asset&&<details><summary>{t("Exact owned source pair","Par de fuentes propias exacto")}</summary><p>MiniSEED: {asset.original_filename} · {asset.byte_count} bytes · {asset.sha256}</p><p>StationXML: {companion?`${companion.original_filename} · ${companion.byte_count} bytes · ${companion.sha256}`:t("Declared companion not available","Acompañante declarado no disponible")}</p><pre>{JSON.stringify({source:asset.source,geometry:asset.physical_metadata.geometry,stationxml_source:companion?.source},null,2)}</pre></details>}
    <label><input type="checkbox" disabled={busy||!asset||!companion||Boolean(requestErrors.length)} checked={Boolean(binding)&&reviewedBinding===binding} onChange={e=>setReviewedBinding(e.target.checked?binding:"")}/>{t("I reviewed this exact request against the selected original pair","Revisé esta solicitud exacta contra el par original seleccionado")}</label>
    <button className="btn" disabled={!ready||busy||!asset||!companion||Boolean(requestErrors.length)||!binding||reviewedBinding!==binding} onClick={()=>void act(async signal=>{if(binding!==reviewedBinding||draftIssues(request).length)throw new Error(t("Review the exact source-bound request first","Revise primero la solicitud vinculada a fuente exacta"));const r=await clients.wave.index(projectId,assetId,JSON.parse(request),signal);if(signal.aborted)return;setReceipts(rows=>rows.some(row=>row.dataset_id===r.dataset_id)?rows:[...rows,r]);setDatasetId(r.dataset_id);setJobId("");})}>{t("Index exact pair and request","Indexar par y solicitud exactos")}</button>
    </div>},{id:"request",label:t("Scientific request","Solicitud científica"),content:<div className="processing-controls">
    <WaveformRequestControls request={request} onChange={setRequest} es={es} disabled={busy} advanced={<>
    <label className="select-control">{t("Explicit scientific request JSON","Solicitud científica JSON explícita")}<textarea className="select" aria-label={t("Scientific request JSON","Solicitud científica JSON")} value={request} onChange={e=>setRequest(e.target.value)} rows={6} maxLength={65536}/></label>
    <label>{t("Load request file","Cargar archivo de solicitud")}<input type="file" accept=".json,application/json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void act(async signal=>{if(file.size>65536)throw new Error(t("Request exceeds 64 KiB","Solicitud supera 64 KiB"));const text=await file.text();if(!signal.aborted)setRequest(text);});}}/></label>
    <button className="btn" disabled={busy||!request.trim()} onClick={()=>download(new Blob([request],{type:"application/json"}),"waveform-scientific-request.json")}>{t("Save explicit request JSON","Guardar solicitud JSON explícita")}</button></>}/>
    </div>},{id:"jobs",label:t("Jobs","Trabajos"),content:<div className="processing-controls">
    <label className="select-control">{t("Immutable dataset","Conjunto inmutable")}<select className="select" value={datasetId} disabled={busy} onChange={e=>{setDatasetId(e.target.value);setJobId("");}}><option value="">{t("Select dataset","Seleccionar conjunto")}</option>{receipts.map(r=><option key={r.dataset_id} value={r.dataset_id}>{r.dataset_id.slice(0,8)} · {r.row_count} {t("samples","muestras")}</option>)}</select></label>
    {methods?.unavailable.map(m=><p key={m.method_id} role="status">{m.reason}</p>)}
    {dataset&&<button className="btn" disabled={busy} onClick={()=>{setAssetId(dataset.raw_asset_id);setRequest(JSON.stringify(dataset.request,null,2));setReviewedBinding("");}}>{t("Edit indexed request as a new draft","Editar solicitud indexada como nuevo borrador")}</button>}
    <button className="btn" disabled={!dataset||!receipt||!enabled||active||busy} onClick={()=>void act(async signal=>{if(!receipt||!dataset)return;const j=await clients.wave.submitWaveform(projectId,receipt,dataset,signal);if(signal.aborted)return;setJobs(rows=>[...rows,j]);setJobId(j.job_id);})}>{t("Run full processing","Ejecutar procesamiento completo")}</button>
    <label className="select-control">{t("Job history","Historial de trabajos")}<select className="select" value={jobId} onChange={e=>setJobId(e.target.value)}><option value="">{t("Select job","Seleccionar trabajo")}</option>{history.map(j=><option key={j.job_id} value={j.job_id}>{j.job_id.slice(0,8)} · {stateLabel(j.state)}</option>)}</select></label>
    {job&&<><p role="status">{stateLabel(job.state)} {job.error?.code}</p><button className="btn" disabled={busy||!["queued","running"].includes(job.state)||job.cancel_requested} onClick={()=>void act(async signal=>{const j=await clients.wave.cancel(projectId,job.job_id,signal);if(!signal.aborted&&j.method_id===WAVEFORM_METHOD)setJobs(rows=>rows.map(row=>row.job_id===j.job_id?j:row));})}>{t("Cancel job","Cancelar trabajo")}</button><details><summary>{t("Submitted parameters and limits","Parámetros enviados y límites")}</summary><pre>{JSON.stringify(job.request.scientific_request,null,2)}</pre><p>{job.preflight.memory_limit_bytes/1048576} MiB · {job.preflight.scratch_limit_bytes} bytes · {job.preflight.wall_limit_seconds} s</p></details></>}
    </div>}];
  return <WorkbenchLayout rail={sections} railLabel={t("Waveform controls","Controles de ondas")} railHead={<>
    {methodNavigation}
    <div className="instrument-brand"><h1>{t("Own waveform processing","Procesamiento de ondas propias")}</h1></div>
    <button className="btn" onClick={onManage}>{t("Projects · upload originals","Proyectos · cargar originales")}</button><button className="btn" onClick={onCurated}>{t("Curated cases","Casos curados")}</button>
    <button className="btn" disabled={busy} onClick={()=>setRevision(v=>v+1)}>{t("Reload project","Recargar proyecto")}</button>
    {error&&<p role="alert" className="project-error">{error}</p>}
  </>}><section className="instrument-main processing-main"><h2>M08 · {t("QC, response, filter, PSD and unlabelled arrivals","QC, respuesta, filtro, PSD y llegadas sin etiquetas")}</h2>
    {result&&job&&<><p>{result.scientific_status} · {result.calculation.qc.reasons.join(", ")}</p><p>{result.resources.memory_kind==="linux_cgroup_charge"?t("Cgroup memory-charge peak, not RSS","Carga de memoria cgroup máxima, no RSS"):t("Job committed-memory peak, not RSS","Memoria comprometida máxima, no RSS")}: {(result.resources.peak_memory_bytes/1048576).toFixed(1)} MiB · CPU {(result.resources.cpu_ns/1e9).toFixed(3)} s</p>
      <button className="btn" disabled={busy} onClick={()=>void act(async()=>{const bytes=waveformResultBytes(result);if(!bytes)throw new Error(t("Original result bytes unavailable","Bytes originales del resultado no disponibles"));download(new Blob([bytes.buffer as ArrayBuffer],{type:"application/json"}),`waveform-${job.job_id}-receipt.json`);})}>{t("Save exact result and execution receipt","Guardar resultado y comprobante de ejecución exactos")}</button>
      <label>{t("Reopen saved receipt against this successful job","Reabrir comprobante guardado contra este trabajo exitoso")}<input type="file" accept=".json,application/json" disabled={busy||!dataset} onChange={e=>{const file=e.target.files?.[0];if(file&&dataset)void act(async signal=>{if(file.size>WAVEFORM_RESULT_BYTE_CAP)throw new Error(t("Receipt exceeds 4 MiB","Comprobante supera 4 MiB"));setFiles(null);const reopened=await readProtectedWaveform(new Uint8Array(await file.arrayBuffer()),job,dataset);if(!signal.aborted)setResult(reopened);});}}/></label>
      <button className="btn" disabled={busy} onClick={()=>void act(async signal=>{const blob=await clients.wave.waveformExport(projectId,job,result,signal);const decoded=await verifyWaveformZip(blob,result);if(signal.aborted)return;setFiles(decoded);download(blob,`waveform-${job.job_id}.zip`);})}>{t("Verify, plot and export all arrays","Verificar, graficar y exportar todas las matrices")}</button>
      <label>{t("Reopen saved ZIP against this successful job","Reabrir ZIP guardado contra este trabajo exitoso")}<input type="file" accept=".zip,application/zip" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void act(async signal=>{setFiles(null);const decoded=await verifyWaveformZip(f,result);if(!signal.aborted)setFiles(decoded);});}}/></label>
      <label>{t("Measured channel","Canal medido")}<select value={channel} onChange={e=>setChannel(Number(e.target.value))}>{result.calculation.channels.map((_,i)=><option key={i} value={i}>c0{i} · {String((dataset?.request.channels as {channel:string}[]|undefined)?.[i]?.channel??"")}</option>)}</select></label>
      <p>{t("Shared time cursor relative to conditioning start","Cursor temporal compartido desde inicio de acondicionamiento")}: {cursor.toFixed(3)} s</p>
      {dataset&&<><p>{t("Conditioning UTC [start, end)","Acondicionamiento UTC [inicio, fin)")}: {String(dataset.request.conditioning_start_utc)} → {String(dataset.request.conditioning_end_utc)}</p><p>{t("Analysis UTC [start, end)","Análisis UTC [inicio, fin)")}: {String(dataset.request.analysis_start_utc)} → {String(dataset.request.analysis_end_utc)}</p></>}
      <p>{t("Native physical unit from this StationXML channel","Unidad física nativa de este canal StationXML")}: {channelMetadata?.native_unit??t("not evaluable","no evaluable")}. {t("Analysis boundary lines are exclusive at end; edge_valid and time_taper are the actual exported arrays. Filtering is offline and acausal.","Las líneas de análisis son exclusivas al final; edge_valid y time_taper son las matrices exportadas reales. El filtrado es offline y acausal.")}</p>
      {files&&descriptors.filter(d=>["counts","physical_native","filtered_native","characteristic","counts_psd","physical_psd","filtered_psd","edge_valid","time_taper","prefilter_weight"].includes(d.name)).map(d=>{const frequency=d.name.endsWith("psd")||d.name==="prefilter_weight";return <WaveformTrace key={d.name} x={xFor(d.name,arrays[d.name])} y={arrays[d.name]} unit={d.unit} title={d.name} axis={frequency?"f [Hz]":"t [s]"} cursor={frequency?-1:cursor} onCursor={frequency?()=>{}:setCursor} markers={frequency?[]:markers}/>;})}
      {files&&response.curves&&<><p>{t("Instrument response display: amplitude hypot(real, imaginary); principal phase atan2(imaginary, real), not unwrapped. Frequency is the measured exported array; no shared time cursor.","Vista de respuesta instrumental: amplitud hypot(real, imaginaria); fase principal atan2(imaginaria, real), sin desenrollar. La frecuencia es la matriz exportada medida; sin cursor temporal compartido.")}</p><WaveformTrace x={response.curves.frequency} y={response.curves.amplitude} unit={response.curves.amplitudeUnit} title={t("Response amplitude","Amplitud de respuesta")} axis="f [Hz]" cursor={-1} onCursor={()=>{}}/><WaveformTrace x={response.curves.frequency} y={response.curves.phase} unit="rad" title={t("Response principal phase","Fase principal de respuesta")} axis="f [Hz]" cursor={-1} onCursor={()=>{}}/></>}
      {response.error&&<p role="alert">{t("Invalid complex response array contract; response plots withheld.","Contrato inválido de matrices de respuesta compleja; gráficos de respuesta retenidos.")}</p>}
      <details><summary>{t("Exact unlabelled trigger intervals","Intervalos de disparo exactos sin etiquetas")}</summary><p>{t("Sample indices are conditioning-relative, with exclusive stop. phase=null and timing_sigma_s=null; these are not P/S picks.","Índices relativos al acondicionamiento, fin exclusivo. phase=null y timing_sigma_s=null; no son llegadas P/S.")}</p>
        {result.calculation.candidates===null?<p>{t("Not evaluable: scientific QC-only.","No evaluable: solo QC científico.")}</p>:result.calculation.candidates.length===0?<p>{t("No trigger intervals in the exact analysis window.","Sin intervalos de disparo en la ventana exacta de análisis.")}</p>:result.calculation.candidates.map((value,i)=>{const row=value as Record<string,unknown>;return <dl key={i}><dt>{t("Unlabelled interval","Intervalo sin etiqueta")} {i+1} · c0{String(row.channel_index)}</dt><dd>UTC: {String(row.on_utc)}</dd><dd>{t("Sample interval [on, off)","Intervalo de muestras [inicio, fin)")}: [{String(row.on_index)}, {String(row.off_exclusive_index)}) · {t("Peak sample / ratio","Muestra máxima / razón")}: {String(row.peak_index)} / {String(row.peak_ratio)}</dd><dd>{t("Onset relative to conditioning","Inicio relativo al acondicionamiento")}: {String(row.on_relative_s)} s · {t("Truncated at valid start/end","Truncado en inicio/fin válido")}: {String(row.truncated_at_valid_start)} / {String(row.truncated_at_valid_end)}</dd></dl>;})}
        <details><summary>{t("Exact trigger JSON","JSON exacto de disparos")}</summary><pre>{JSON.stringify(result.calculation.candidates,null,2)}</pre></details></details>
      <details><summary>{t("QC, edge masks, response and pick provenance","QC, máscaras de borde, respuesta y procedencia de llegadas")}</summary><pre>{JSON.stringify(result.calculation,null,2)}</pre></details>
    </>}
    <p>{t("No P/S reassignment, catalogue tuning or invented uncertainty. Offline zero-phase filtering is acausal. These results do not establish subsurface truth or host acceptance.","Sin reasignación P/S, ajuste al catálogo ni incertidumbre inventada. El filtro offline de fase cero es acausal. Estos resultados no establecen verdad del subsuelo ni aceptación del host.")}</p>
  </section></WorkbenchLayout>;
}
