"""Adversarial source-bound MT replay checks; local offline lane only."""

from copy import deepcopy
import importlib.util
import json
from pathlib import Path

import pytest
import torch

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location('mt_replay_checker', ROOT / 'scripts/validate_mt_replays.py')
checker = importlib.util.module_from_spec(spec)
spec.loader.exec_module(checker)


@pytest.fixture(scope='module')
def golden():
    from electromagnetics import solve_case
    from rebuild import annotate, jsonable
    torch.set_num_threads(1)
    case = next(case for case in checker.registry() if case['id'] == 'MT_RESISTIVE')
    run = jsonable(annotate(solve_case(case, 'reference'), case, 0.))
    return case, run


def test_complete_matrix_and_source_binding(golden):
    case, run = golden
    catalog = dict(complete=False, cases=[dict(id=c['id'], variants=[dict(id=v) for v, _, _ in checker.VARIANTS])
                                         for c in checker.registry() if c['family'] == 'mt'])
    _, expected = checker.validate_matrix(catalog)
    assert len(expected) == 24
    partial = deepcopy(catalog)
    partial['cases'][0]['variants'].pop()
    with pytest.raises(AssertionError, match='24-condition'):
        checker.validate_matrix(partial)
    duplicate = deepcopy(catalog)
    duplicate['cases'][0]['variants'][0]['id'] = duplicate['cases'][0]['variants'][1]['id']
    with pytest.raises(AssertionError, match='24-condition'):
        checker.validate_matrix(duplicate)
    assert len(checker.validate_condition(run, case, 'reference', run, replay_bootstrap=False)) == 3
    wrong_source = deepcopy(run)
    wrong_source['provenance']['generator_fingerprint'] = '0' * 64
    with pytest.raises(AssertionError):
        checker.validate_condition(wrong_source, case, 'reference', run, replay_bootstrap=False)
    wrong_input = deepcopy(run)
    wrong_input['observed']['real'][0] += 1
    with pytest.raises(AssertionError, match='Seeded source mismatch'):
        checker.validate_condition(wrong_input, case, 'reference', run, replay_bootstrap=False)


@pytest.mark.parametrize('target', ['prediction', 'residual', 'history', 'uncertainty', 'budget', 'verdict'])
def test_rehashed_numerical_tamper_fails(golden, target):
    case, reference = golden
    run = deepcopy(reference)
    method = run['methods']['mt-lm']
    if target == 'prediction':
        method['predicted']['real'][0] *= 2
    elif target == 'residual':
        method['residual']['imag'][0] += .1
    elif target == 'history':
        method['history'][-1] += 1
    elif target == 'uncertainty':
        method['uncertainty']['mean'][0] *= 2
    elif target == 'budget':
        method['solver']['max_nfev'] = 4
    else:
        method['evaluation']['status'] = 'failed'
    # Byte hashes may be regenerated by an assembler; numerical checking must
    # reject the parsed content independently of those integrity receipts.
    with pytest.raises(AssertionError):
        checker.validate_condition(run, case, 'reference', reference, replay_bootstrap=False)


def test_field_screen_requires_original_bytes(tmp_path):
    source = tmp_path / 'USGS-GMEG.2022.cl061.edi'
    source.write_bytes(b'Not the pinned measured original')
    with pytest.raises(AssertionError, match='Pinned cl061 original required'):
        checker.validate_field(tmp_path, source)


def test_field_receipt_rehashed_eligibility_tamper(tmp_path):
    from build_field_screen import build
    source = ROOT / 'data/downloads/clear-lake/USGS-GMEG.2022.cl061.edi'
    if not source.is_file():
        pytest.skip('Acquire the pinned local cl061 original for the actual-byte field gate')
    edi = tmp_path / 'edi'
    edi.mkdir()
    manifest = edi / 'manifest.json'
    manifest.write_bytes((ROOT / 'data/derived/v2/edi/manifest.json').read_bytes())
    build(source, tmp_path)
    assert checker.validate_field(tmp_path, source)['one_d_inversion_eligible'] is False
    artifact = edi / 'clear-lake-cl061-screen.json'
    run = json.loads(artifact.read_text(encoding='utf-8'))
    run['one_d_inversion_eligible'] = True
    artifact.write_text(json.dumps(run), encoding='utf-8')
    receipt = json.loads(manifest.read_text(encoding='utf-8'))
    receipt['field_screens'][0].update(artifact_sha256=checker.digest(artifact),
                                     artifact_bytes=artifact.stat().st_size, one_d_inversion_eligible=True)
    manifest.write_text(json.dumps(receipt), encoding='utf-8')
    with pytest.raises(AssertionError, match='Fresh cl061 screen differs'):
        checker.validate_field(tmp_path, source)
