import { ApiClient } from "./client";
import { ProcessingApi } from "./processing";
import { processingObject as obj, processingId as id, processingText as text, same, parseProjectDatasetReceipt, parseProjectProcessingJob } from "./processing-contracts";
import { WAVEFORM_METHOD, parseWaveformDataset, parseWaveformResult, bindWaveformResult, verifyWaveformZip, type WaveformReceipt, type WaveformDataset, type WaveformJob, type WaveformResult } from "./waveform-contracts";
export * from "./waveform-contracts";

export class WaveformApi extends ProcessingApi {
  constructor(private readonly client:ApiClient){super(client);}
  private root(project:string){return `/api/projects/${id(project)}`;}
  private async token(signal?:AbortSignal){return text((await this.client.requestJson("/api/auth/csrf",v=>obj(v,"csrf"),{signal})).csrf_token,"CSRF");}
  async index(project:string,asset:string,request:Record<string,unknown>,signal?:AbortSignal){if(new TextEncoder().encode(JSON.stringify(request)).length>65536)throw new Error("Waveform request cap");const receipt=await this.client.requestJson(`${this.root(project)}/datasets`,parseProjectDatasetReceipt,{method:"POST",csrfToken:await this.token(signal),body:{asset_id:id(asset),waveform_request:request},signal});if(receipt.modality!=="waveform_counts_response")throw new Error("Non-waveform receipt");same(receipt.project_id,project,"waveform project");same(receipt.raw_asset_id,asset,"waveform original");return receipt;}
  async waveformDataset(project:string,receipt:WaveformReceipt,signal?:AbortSignal){const dataset=await this.client.requestJson(`${this.root(project)}/datasets/${id(receipt.dataset_id)}`,parseWaveformDataset,{signal});same(dataset.project_id,project,"waveform project");same(dataset.dataset_id,receipt.dataset_id,"waveform dataset");same(dataset.parent_raw_sha256,receipt.raw_sha256,"waveform original");return dataset;}
  async submitWaveform(project:string,receipt:WaveformReceipt,dataset:WaveformDataset,signal?:AbortSignal){const job=await this.client.requestJson(`${this.root(project)}/jobs`,parseProjectProcessingJob,{method:"POST",csrfToken:await this.token(signal),body:{dataset_id:receipt.dataset_id,method_id:WAVEFORM_METHOD,parameters:{scientific_request_sha256:dataset.scientific_request_sha256}},signal});if(job.method_id!==WAVEFORM_METHOD)throw new Error("Non-waveform job");same(job.project_id,project,"waveform project");same(job.dataset_id,receipt.dataset_id,"waveform dataset");same(job.dataset_sha256,receipt.sha256,"waveform dataset hash");same(job.request.scientific_request,dataset.request,"immutable scientific request");same(job.request.waveform_sources,dataset.sources,"immutable original pair");return job;}
  async waveformResult(project:string,job:WaveformJob,dataset:WaveformDataset,signal?:AbortSignal){if(job.state!=="succeeded")throw new Error("Waveform result not ready");const result=await this.client.requestJson(`${this.root(project)}/jobs/${id(job.job_id)}/result`,parseWaveformResult,{signal});bindWaveformResult(result,job,dataset);return result;}
  async waveformExport(project:string,job:WaveformJob,result:WaveformResult,signal?:AbortSignal){same(job.project_id,project,"waveform project");same(result.job_id,job.job_id,"waveform job");if(job.state!=="succeeded")throw new Error("Waveform export not ready");const blob=await this.client.requestBlob(`${this.root(project)}/jobs/${id(job.job_id)}/export`,{signal});await verifyWaveformZip(blob,result);return blob;}
}
