import { Callout, Equation, Refs, SubTabs, useShellLang } from '@fasl-work/caos-app-shell';

const families: Array<[string, string, string, string, string[]]> = [
  ['Potential fields', 'Gravity and magnetics are integral operators over density and magnetization. The surface response is smooth and non-local, so depth weighting and compactness are not cosmetic choices: they express a prior about how sensitivity decays with distance. The build reports the inducing angle and the scalar susceptibility assumption next to every response. A body that is deep, thin, or directionally mismatched is intentionally difficult.', 'g = G\\rho', 'Gravity and magnetics map a subsurface contrast to a surface field.', ['cockett2015','choclo']],
  ['Layered MT', 'The MT module treats the earth as horizontal layers, propagates a complex impedance from the half-space upward, and converts impedance magnitude to apparent resistivity. Frequencies do not sample a fixed depth; the skin effect couples period and conductivity. The browser exposes the frequency axis in logarithmic space and keeps phase visible so a low misfit cannot hide a phase failure.', 'Z_j = Z_{0j}\\frac{1-r_j e^{-2 k_j h_j}}{1+r_j e^{-2 k_j h_j}}', 'Layer recursion carries complex impedance across each finite layer.', ['heagy2017','mtpy']],
  ['Physics-guided learning', 'The learned MT view is a tool, not a decorative score. Its parameterization is bounded in log resistivity, the forward response remains in the loss, and a smoothness term penalizes unstable layer-to-layer jumps. The held-out split is grouped by case so nearby frequencies from the same model cannot leak across train and test. The result is a comparison between a learned parameterization and a transparent deterministic baseline.', '\\mathcal{L}=\\|\\log|Z_\\theta|-\\log|Z_{obs}|\\|_2^2+\\lambda\\|\\nabla \\log \\rho_\\theta\\|_2^2', 'The loss joins data misfit and a smoothness prior.', ['goyes2024','pinnreview']],
  ['Acoustic FWI', 'The acoustic track evolves a pressure field with a second-order time stencil. Source and receiver geometry are explicit. A residual is correlated with the predicted wavefield to form one update, then the update is clipped to a physical range. Frequency continuation is a control because a high-frequency phase error can place the optimizer in the wrong basin. This compact case is suitable for a transparent certificate and GPU acceleration, but it is not a field-scale elastic inversion.', 'u_{tt}=v^2\\nabla^2u+s', 'The acoustic wave equation couples phase, speed, and geometry.', ['virieux2009','deepwave','devito']],
  ['Learned spatial prior', 'The CNN field-prior tab uses a labelled surrogate representation to ask a narrower question: does a spatial prior reduce a reconstruction error on cases it did not see? The app does not ship a hand-written accuracy claim. It reports the generated case, split policy, response residual, and a novelty guard. The autoencoder view complements the prior by showing when a reconstruction leaves the training manifold.', '\\hat m = f_\\theta(d), \\quad e_{novel}=\\|d-g_\\phi(f_\\theta(d))\\|_2', 'A learned prediction is paired with a reconstruction-based guard.', ['openfwi','inversionnet']],
  ['Joint evidence', 'Cross-gradient coupling asks whether two model images share structural changes, not whether their amplitudes are identical. The determinant of horizontal and vertical gradients is near zero when boundaries align. The app uses this as a diagnostic layer beside the separate gravity and magnetic responses. Conflict is preserved: forcing agreement can erase a real physics-specific target.', '\\phi(m_1,m_2)=\\nabla m_1\\times\\nabla m_2', 'The cross-gradient measures structural disagreement between models.', ['cockett2015','heagy2017']],
];

export default function Methodology() { const es = useShellLang() === 'es'; return <div className="page-body prose"><div className="page-head"><h1>{es ? 'Metodología' : 'Methodology'}</h1><p className="lede">{es ? 'Seis familias y una frontera explícita entre física, prior y evidencia. Cada tab conserva supuestos, ecuaciones, fallas y referencias.' : 'Six families and an explicit boundary between physics, prior, and evidence. Each tab keeps assumptions, equations, failure modes, and references.'}</p></div><SubTabs orientation="vertical" ariaLabel="Method families" tabs={families.map(([title, body, formula, caption, refs]) => ({ id: String(title).toLowerCase().replaceAll(' ', '-'), label: title, content: <section className="method-doc"><h2>{title}</h2><p>{body}</p><p>{es ? 'La implementación fija el significado de cada símbolo, registra unidades y conserva una salida reejecutable.' : 'The implementation fixes the meaning of each symbol, records units, and retains a replayable output.'}</p><Equation tex={formula} caption={caption} /><p>{es ? 'Cuándo usarlo: como prueba controlada de sensibilidad y como comparación entre hipótesis. Cuándo falla: cobertura insuficiente, geometría incorrecta, ruido no modelado o una prior que domina los datos.' : 'When to use it: as a controlled sensitivity test and comparison between hypotheses. When it fails: insufficient coverage, incorrect geometry, unmodelled noise, or a prior that dominates the data.'}</p><p>{es ? 'La vista del workbench enlaza el campo con la respuesta y el residuo; mover contraste, profundidad, ángulo o ruido modifica la salida, de modo que la interactividad conserva significado físico.' : 'The workbench links the field to response and residual; moving contrast, depth, angle, or noise modifies the output, so interaction retains physical meaning.'}</p><Callout variant="honest" title={es ? 'Límite' : 'Boundary'}>{es ? 'Un modelo sintético controlado demuestra la lógica del método, no garantiza identificación en una campaña real.' : 'A controlled synthetic model demonstrates method logic; it does not guarantee identifiability in a field campaign.'}</Callout><Refs ids={refs as string[]} label={es ? 'Referencias' : 'References'} /></section> }))} /></div>; }
