import { useMemo, useState } from 'react';
import { BarChart3, Database, Gauge, Pause, Play, RotateCcw, Waves } from 'lucide-react';
import { Callout, Equation, SubTabs, Tabs, usePausedViz, useShellLang } from '@fasl-work/caos-app-shell';
import { CASES, makeLiveResult, type CaseParams } from '../engine';
import { Section } from '../components/Viz';

const methods = [
  ['gravity-forward', 'Gravity forward', 'gravity', 'Point-mass kernel with depth-aware geometry.'], ['gravity-inverse', 'Gravity inverse', 'gravity', 'Weighted L2 and smoothness context.'], ['gravity-irls', 'Gravity sparse IRLS', 'gravity', 'Reweighted model norm exposes compact support.'], ['magnetic-forward', 'Magnetic forward', 'magnetics', 'Induced total-field response under a rotated field.'], ['magnetic-vector', 'Magnetic vector', 'magnetics', 'Vector-direction sensitivity and remanence caveat.'], ['mt-layered', 'MT layered earth', 'mt', 'Recursive impedance for finite resistive and conductive layers.'], ['mt-differentiable', 'MT differentiable', 'mt', 'Complex impedance loss with smooth log-resistivity.'], ['mt-guided', 'MT physics-guided', 'mt', 'Neural parameterization constrained by the forward operator.'], ['fwi-acoustic', 'Acoustic FWI', 'fwi', 'Finite-difference shot, residual, and one update.'], ['fwi-multiscale', 'FWI frequency continuation', 'fwi', 'Low-to-high frequency path to reduce cycle skipping.'], ['cnn-prior', 'CNN field prior', 'learned', 'Held-out learned spatial prior with an evidence guard.'], ['autoencoder', 'Autoencoder novelty', 'learned', 'Latent reconstruction error for out-of-distribution structure.'], ['joint-cross', 'Joint cross-gradient', 'joint', 'Structural agreement between gravity and magnetics.'],
] as const;

function Slider({ label, value, min, max, step, unit, onChange, hint }: { label: string; value: number; min: number; max: number; step: number; unit: string; onChange: (v: number) => void; hint: string }) {
  return <label className="control"><span><b>{label}</b><small>{hint}</small></span><span className="control-value">{value.toFixed(step < 1 ? 2 : 0)} {unit}</span><input title={`${label}: ${hint}`} type="range" min={min} max={max} step={step} value={value} onChange={(e) => onChange(Number(e.target.value))} /></label>;
}

function MethodContent({ method, result }: { method: typeof methods[number]; result: ReturnType<typeof makeLiveResult> }) {
  const [sub, setSub] = useState('field'); const [lang] = [useShellLang()];
  const note = lang === 'es' ? 'El resultado cambia con el caso y con los controles físicos del panel.' : 'The result changes with the selected case and the physical controls in the panel.';
  return <div><div className="method-head"><div><span className="eyebrow">{method[0]}</span><h2>{method[1]}</h2><p>{method[3]} {note}</p></div><span className="status-pill"><span className="status-dot" /> live analytic lane</span></div><SubTabs ariaLabel="Method evidence views" tabs={[
    { id: 'field', label: lang === 'es' ? 'Campo' : 'Field', content: <Section result={result} mode={method[2]} opacity={1} /> },
    { id: 'residual', label: lang === 'es' ? 'Residuo' : 'Residual', content: <><LineSummary result={result} method={method} /><Callout variant="honest" title={lang === 'es' ? 'Alcance honesto' : 'Honest scope'}>{lang === 'es' ? 'El carril en vivo es un motor analítico compacto. El bake offline conserva los artefactos canónicos y el solver completo.' : 'The live lane is a compact analytic engine. The offline bake retains canonical artifacts and the full solver path.'}</Callout></> },
    { id: 'context', label: lang === 'es' ? 'Contexto' : 'Context', content: <div className="context-block"><Equation tex={method[2] === 'mt' ? 'Z = \sqrt{i\\omega\\mu\\rho_a}' : method[2] === 'fwi' ? 'u_{tt} - v^2\\nabla^2u = s' : 'd = F(m) + \\varepsilon'} caption={lang === 'es' ? 'Relación física que organiza la lectura de esta vista.' : 'Physical relation organizing this view.'} /><p>{lang === 'es' ? 'El modelo no es una verdad única: la visualización mantiene la observación, la respuesta y la evidencia de identificabilidad cerca.' : 'The model is not a unique truth: the visualization keeps observation, response, and identifiability evidence together.'}</p></div> },
  ]} initial={sub} />{void setSub}</div>;
}

function LineSummary({ result, method }: { result: ReturnType<typeof makeLiveResult>; method: typeof methods[number] }) { const values = method[2] === 'magnetics' ? result.magnetic : method[2] === 'mt' ? result.resistivity : method[2] === 'fwi' ? result.residual : result.gravity; const peak = Math.max(...values.map(Math.abs)); return <div className="metric-strip"><div><span>peak response</span><strong>{peak.toPrecision(5)}</strong></div><div><span>samples</span><strong>{values.length}</strong></div><div><span>noise setting</span><strong>{(result.uncertainty[0] * 100).toFixed(1)}%</strong></div></div>; }

export default function Workbench() {
  const lang = useShellLang(); const [selected, setSelected] = useState(CASES[0].id); const base = CASES.find((c) => c.id === selected) ?? CASES[0]; const [params, setParams] = useState<CaseParams>(base.params); const [slice, setSlice] = useState(0); const [opacity, setOpacity] = useState(1); const [angleStep, setAngleStep] = useState(12);
  const update = (key: keyof CaseParams, value: number) => setParams((current) => ({ ...current, [key]: value }));
  const result = useMemo(() => makeLiveResult({ ...params, depth: params.depth + slice * 12 }, 42, 32), [params, slice]);
  const animation = usePausedViz((_dt, elapsed) => { update('angle_deg', (params.angle_deg + elapsed * angleStep / 80) % 360); return true; }, { loop: true, durationMs: 12000 });
  const caseGroups = useMemo(() => CASES.reduce<Record<string, typeof CASES>>((a, c) => { (a[c.category] ??= []).push(c); return a; }, {}), []);
  return <div className="page-body studio-layout"><aside className="studio-side"><div className="side-kicker"><Gauge size={16} /> {lang === 'es' ? 'Instrumento activo' : 'Active instrument'}</div><h1>{lang === 'es' ? 'Cartografía de evidencia' : 'Evidence cartography'}</h1><p className="side-copy">{lang === 'es' ? 'Una lectura sincronizada de observación, modelo, residuo e identificabilidad.' : 'A synchronized reading of observation, model, residual, and identifiability.'}</p>
    <label className="control"><span><b>{lang === 'es' ? 'Caso / escenario' : 'Case / scenario'}</b><small>{base.category}</small></span><select value={selected} onChange={(e) => { const next = CASES.find((c) => c.id === e.target.value) ?? CASES[0]; setSelected(next.id); setParams(next.params); }} title="Choose a reproducible case">{Object.entries(caseGroups).map(([cat, items]) => <optgroup key={cat} label={cat}>{items.map((c) => <option key={c.id} value={c.id}>{c.id}</option>)}</optgroup>)}</select></label>
    <div className="case-description">{base.description}</div><div className="control-group"><Slider label="Contrast" value={params.anomaly} min={.4} max={2.2} step={.05} unit="contrast" hint="density/susceptibility scale" onChange={(v) => update('anomaly', v)} /><Slider label="Target depth" value={params.depth} min={240} max={1350} step={10} unit="m" hint="centre of the synthetic body" onChange={(v) => update('depth', v)} /><Slider label="Conductivity" value={params.conductivity} min={.2} max={5} step={.1} unit="relative" hint="layered MT contrast" onChange={(v) => update('conductivity', v)} /><Slider label="Noise" value={params.noise} min={0} max={.18} step={.005} unit="sigma" hint="observation perturbation" onChange={(v) => update('noise', v)} /><Slider label="Field angle" value={params.angle_deg} min={0} max={360} step={1} unit="deg" hint="survey or inducing-field azimuth" onChange={(v) => update('angle_deg', v)} /><Slider label="Depth slice" value={slice} min={-12} max={12} step={1} unit="cells" hint="inspect nearby model slices" onChange={setSlice} /><Slider label="Angle step" value={angleStep} min={2} max={32} step={1} unit="deg/frame" hint="rotation speed for evidence animation" onChange={setAngleStep} /><Slider label="Layer opacity" value={opacity} min={.35} max={1} step={.05} unit="alpha" hint="overlay strength for the field map" onChange={setOpacity} /></div>
    <div className="run-controls"><button className="button primary" onClick={animation.toggle}>{animation.playing ? <Pause size={15} /> : <Play size={15} />}{animation.playing ? 'Pause' : 'Animate'}</button><button className="button" onClick={animation.restart}><RotateCcw size={15} /> Reset</button></div><div className="diagnosis"><span className="eyebrow">{lang === 'es' ? 'Lectura actual' : 'Current reading'}</span><strong>{params.noise > .08 ? 'Sensitivity exposed' : 'Structure resolved'}</strong><small>depth {params.depth.toFixed(0)} m · angle {params.angle_deg.toFixed(0)} deg</small></div>
  </aside><section className="studio-main"><div className="studio-banner"><div><span className="eyebrow">{base.method}</span><h2>{selected.replaceAll('_', ' ')}</h2><p>{lang === 'es' ? 'Explora el mismo caso a través de métodos físicos y aprendidos.' : 'Explore the same case through physical and learned methods.'}</p></div><div className="banner-badges"><span><Database size={14} /> replay ready</span><span><Waves size={14} /> GPU baked</span></div></div><Tabs ariaLabel="Geophysics methods" tabs={methods.map((method) => ({ id: method[0], label: method[1], content: <MethodContent method={method} result={result} /> }))} /><div className="status-bar"><span>run: {selected}</span><span>seed: 42</span><span>lane: live + replay</span><span>grid: {result.x.length} × {result.z.length}</span><span><BarChart3 size={14} /> pointer readout enabled</span></div></section></div>;
}
