import { afterEach, describe, expect, it, vi } from "vitest";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { zipSync } from "fflate";
import actual from "./fixtures/waveform-authored-calculation.json";
import { ApiClient } from "../api/client";
import { WaveformApi, WAVEFORM_METHOD, isWaveformJob, isWaveformReceipt, parseWaveformDataset, parseWaveformResult, decodeWaveformArray, verifyWaveformZip, type WaveformResult, type WaveformJob } from "../api/waveform";
import { isMtJob, isEdiReceipt, parseProjectDatasetReceipt, sha } from "../api/processing-contracts";
import { WaveformProjectWorkbench, WaveformTrace } from "../components/WaveformProjectWorkbench";

const uuid="00000000-0000-4000-8000-000000000001", digest="a".repeat(64);
function result():WaveformResult {
  const calculation=structuredClone(actual), sources=Object.fromEntries(["miniseed","stationxml"].map(role=>[role,{asset_id:uuid,source_id:uuid,source_version:1,raw_sha256:calculation.sources[role as "miniseed"|"stationxml"].raw_sha256,raw_bytes:calculation.sources[role as "miniseed"|"stationxml"].raw_bytes,rights_decision:"provider-link-only",private_storage_permission:"attested"}]));
  const members=[{name:"calculation.json",bytes:17605,sha256:digest},{name:"receipt.json",bytes:833,sha256:digest},{name:"manifest.json",bytes:2481,sha256:digest},...calculation.array_descriptors.map(d=>({name:`c0${d.channel_index}-${d.name}.bin`,bytes:d.bytes,sha256:d.sha256}))];
  // API-envelope/transport fixture only; resource numbers below are NOT native
  // evidence. The actual authored calculation is from the full Python engine.
  return {schema:"geophysics.waveform-result/v1",job_id:uuid,project_id:uuid,dataset_id:uuid,dataset_sha256:digest,method_id:WAVEFORM_METHOD,request_sha256:digest,scientific_request_sha256:calculation.request.scientific_sha256,sources,scientific_status:"computed",calculation_sha256:digest,calculation,members,resources:{schema:"geophysics.waveform-resources/v1",cpu_ns:1,max_sample_gap_ns:1,peak_memory_bytes:1,memory_kind:"windows_job_committed",native_receipt_sha256:digest,release_sha256:digest,runtime_authorized:false,host_admitted:false}} as unknown as WaveformResult;
}
afterEach(()=>vi.unstubAllGlobals());
describe("M08 owned client and shared-shell views",()=>{
  it("accepts the exact API parser revision and rejects invented or altered parser identities",()=>{
    const r=result(),parser=`m08/v1/${r.scientific_request_sha256}`;
    const receipt={dataset_id:uuid,project_id:uuid,raw_asset_id:uuid,version:1,schema:"geophysics.observation-dataset/v1",modality:"waveform_counts_response",row_count:18000,parser_version:parser,raw_sha256:r.sources.miniseed.raw_sha256,sha256:digest,created_at:"2026-10-08T00:00:00Z",qc_verdict:"structural_index_not_physical_qc"};
    const dataset={schema:"geophysics.waveform-dataset/v1",dataset_id:uuid,project_id:uuid,owner_id:uuid,raw_asset_id:uuid,parent_raw_sha256:receipt.raw_sha256,version:1,parser_version:parser,modality:receipt.modality,dimensions:{channel:1,sample:18000,record:18},sources:r.sources,request:r.calculation.request.submitted,scientific_request_sha256:r.scientific_request_sha256,qc_verdict:receipt.qc_verdict};
    expect(parseProjectDatasetReceipt(receipt)).toEqual(receipt);expect(parseWaveformDataset(dataset)).toEqual(dataset);
    for(const bad of [`m08-counts-response/v1/${r.scientific_request_sha256}`,`m08/v1/${"g".repeat(64)}`]){expect(()=>parseProjectDatasetReceipt({...receipt,parser_version:bad})).toThrow();expect(()=>parseWaveformDataset({...dataset,parser_version:bad})).toThrow();}
    expect(()=>parseWaveformDataset({...dataset,scientific_request_sha256:digest})).toThrow();
  });
  it("accepts an actual authored calculation without granting scientific authority",()=>{const r=result();expect(parseWaveformResult(r)).toEqual(r);expect(r.calculation.field_truth).toBeNull();expect(Object.values(r.calculation.acceptance).every(v=>v===false)).toBe(true);});
  it.each(["schema","authority","rss","gap","channel","dtype","size","hash","extra"])("rejects %s contract drift",kind=>{const r=result();if(kind==="schema")r.calculation.schema="future";if(kind==="authority")r.calculation.acceptance.host_admitted=true as false;if(kind==="rss")r.resources.memory_kind="rss" as "windows_job_committed";if(kind==="gap")r.resources.max_sample_gap_ns=100000001;if(kind==="channel")r.calculation.channels[0].sample_rate_hz=NaN;if(kind==="dtype")r.calculation.array_descriptors[0].dtype="<i4";if(kind==="size")r.members[3].bytes++;if(kind==="hash")r.members[3].sha256=digest;if(kind==="extra")r.members.push({name:"raw.ms",bytes:1,sha256:digest});expect(()=>parseWaveformResult(r)).toThrow();});
  it("keeps waveform jobs/receipts out of MT and gravity unions using positive guards",()=>{expect(isWaveformJob({method_id:WAVEFORM_METHOD})).toBe(true);expect(isWaveformJob({method_id:"gravity.station-outlier-flags/v1"})).toBe(false);expect(isMtJob({method_id:WAVEFORM_METHOD} as never)).toBe(false);expect(isEdiReceipt({modality:"waveform_counts_response"} as never)).toBe(false);expect(isWaveformReceipt({modality:"waveform_counts_response"})).toBe(true);});
  it("refuses unfinished result/export without network calls",async()=>{const api=new WaveformApi(new ApiClient("http://127.0.0.1:8877")),fetch=vi.fn(),job={state:"queued",project_id:uuid,job_id:uuid} as WaveformJob;vi.stubGlobal("fetch",fetch);await expect(api.waveformResult(uuid,job,{} as never)).rejects.toThrow("not ready");await expect(api.waveformExport(uuid,job,result())).rejects.toThrow("not ready");expect(fetch).not.toHaveBeenCalled();});
  it("rejects over-cap submitted requests before obtaining a CSRF token",async()=>{const fetch=vi.fn();vi.stubGlobal("fetch",fetch);await expect(new WaveformApi(new ApiClient("http://127.0.0.1:8877")).index(uuid,uuid,{text:"x".repeat(65536)})).rejects.toThrow("cap");expect(fetch).not.toHaveBeenCalled();});
  it("decodes exact little-endian arrays and rejects nonfinite/bool corruption",()=>{const d={channel_index:0,name:"counts",dtype:"<i4" as const,shape:[2],unit:"counts",bytes:8,sha256:digest};expect(decodeWaveformArray(new Uint8Array([1,0,0,0,255,255,255,255]),d)).toEqual([1,-1]);expect(()=>decodeWaveformArray(new Uint8Array(7),d)).toThrow();const nan=new Uint8Array(8);new DataView(nan.buffer).setFloat64(0,NaN,true);expect(()=>decodeWaveformArray(nan,{...d,dtype:"<f8"})).toThrow();expect(()=>decodeWaveformArray(new Uint8Array([2]),{...d,dtype:"|b1",bytes:1,shape:[1]})).toThrow();});
  it("verifies ZIP transport seals before plotting, rejecting extra/compressed/tampered members",async()=>{const r=result(),encode=(v:unknown)=>new TextEncoder().encode(JSON.stringify(v));const files={"calculation.json":encode(r.calculation),"receipt.json":encode({transport_test_only:true}),"manifest.json":encode({transport_test_only:true})};r.members=await Promise.all(Object.entries(files).map(async([name,bytes])=>({name,bytes:bytes.length,sha256:await sha(bytes)})));r.calculation_sha256=r.members[0].sha256;const blob=(entries:Record<string,Uint8Array>,level:0|1=0)=>new Blob([Uint8Array.from(zipSync(entries,{level})).buffer]);expect(await verifyWaveformZip(blob(files),r)).toEqual(files);for(const bad of [blob({...files,"raw.ms":encode("forbidden")}),blob(files,1),blob({...files,"calculation.json":encode({...r.calculation,field_truth:[1]})})])await expect(verifyWaveformZip(bad,r)).rejects.toThrow();});
  it.each([false,true])("renders the existing shell with explicit controls and scientific limits, Spanish=%s",es=>{const html=renderToStaticMarkup(createElement(WaveformProjectWorkbench,{projectId:uuid,es,onManage:()=>{},onCurated:()=>{}}));expect(html).toContain("instrument-sidebar processing-sidebar");expect(html).toContain("instrument-main processing-main");expect(html).toContain(es?"Solicitud científica JSON":"Scientific request JSON");expect(html).toContain(es?"fase cero es acausal":"zero-phase filtering is acausal");expect(html).toContain(es?"Sin reasignación P/S":"No P/S reassignment");expect(html).not.toContain("font-family");});
  it("renders exact extrema and physical units without modifying source arrays",()=>{const y=[1,7,-5,2],before=JSON.stringify(y);const html=renderToStaticMarkup(createElement(WaveformTrace,{x:[0,1,2,3],y,unit:"m/s",title:"Velocity",cursor:1,onCursor:()=>{}}));expect(html).toContain("Velocity; t [s]; m/s");expect(html).toContain("polyline");expect(JSON.stringify(y)).toBe(before);});
});
