import type { ArchitectureConfig } from '@fasl-work/caos-app-shell';

export const architecture: ArchitectureConfig = { tabs: [
  { id: 'app', en: 'The app', es: 'La app', svg: 'svg/tech/01-the-app.svg', body_en: 'Inverse Earth Studio is a real geophysics workbench for inspecting how gravity, magnetics, magnetotellurics, and acoustic waves constrain a subsurface model. A selected case and physical controls alter the live fields, residuals, evidence layers, and uncertainty story. It is not a field interpreter and it does not hide non-uniqueness behind a single score.', body_es: 'Inverse Earth Studio es un workbench real de geofísica para inspeccionar cómo la gravedad, el magnetismo, la magnetotelúrica y las ondas acústicas restringen un modelo del subsuelo. Un caso seleccionado y controles físicos cambian los campos, residuos, capas de evidencia y la incertidumbre en vivo. No es un intérprete de campo ni oculta la no unicidad detrás de un único puntaje.' },
  { id: 'lanes', en: 'Web, offline, replay', es: 'Web, offline, replay', svg: 'svg/tech/02-lanes.svg', body_en: 'The browser lane mirrors compact analytic equations for immediate what-if interaction. The offline lane runs the staged Python bake, solver-backed checks, learned baselines, and GPU experiments. Replay artifacts are the checked release truth; the CPU-only mirror serves those artifacts without pretending to provide GPU compute.', body_es: 'El carril del navegador espeja ecuaciones analíticas compactas para interacción inmediata. El carril offline ejecuta el bake Python por etapas, verificaciones con solvers, baselines aprendidos y experimentos GPU. Los artefactos replay son la verdad de release; el espejo CPU-only los sirve sin fingir que entrega cómputo GPU.' },
  { id: 'flow', en: 'Web-app flow', es: 'Flujo web', svg: 'svg/tech/03-web-flow.svg', body_en: 'The selected case loads its manifest and replay artifact. Controls feed the live engine, which recomputes a density and susceptibility field, potential-field lines, layered impedance, wave residuals, joint evidence, and uncertainty. Pointer readouts expose coordinates and units. The six routes separate the tool from the rigorous documentation and benchmark record.', body_es: 'El caso seleccionado carga su manifest y artefacto replay. Los controles alimentan el motor en vivo, que recalcula densidad y susceptibilidad, líneas de campos potenciales, impedancia estratificada, residuos de onda, evidencia conjunta e incertidumbre. Los readouts del puntero exponen coordenadas y unidades. Las seis rutas separan la herramienta de la documentación rigurosa y del registro benchmark.' },
  { id: 'science', en: 'Science flow', es: 'Flujo científico', svg: 'svg/tech/04-the-science.svg', body_en: 'The scientific chain is ingest, preprocess, grouped split, features, train, infer, evaluate, export, validate. Gravity and magnetics use potential-field kernels and regularization context; MT uses layered-earth recursion and a differentiable loss; FWI uses a compact finite-difference acoustic shot; learned views show a labelled surrogate or novelty score, never an unexplained oracle.', body_es: 'La cadena científica es ingesta, preproceso, partición agrupada, features, train, infer, evaluate, export, validate. Gravedad y magnetismo usan kernels de campos potenciales y contexto de regularización; MT usa recursión de tierra estratificada y una pérdida diferenciable; FWI usa un disparo acústico compacto por diferencias finitas; las vistas aprendidas muestran un surrogate o score de novedad etiquetado, nunca un oráculo inexplicado.' },
  { id: 'contracts', en: 'Data contracts', es: 'Contratos de datos', svg: 'svg/tech/05-data-contracts.svg', body_en: 'Contract 1 validates station observations, coordinates, positive frequencies, values, and units with explicit reject and flag rules. Contract 2 validates replay JSON, manifest byte sizes, schema, case identity, and engine provenance. These contracts are the boundary that lets a researcher bring another observation table without silently changing the experiment.', body_es: 'El Contrato 1 valida observaciones de estación, coordenadas, frecuencias positivas, valores y unidades con reglas explícitas de rechazo y marcado. El Contrato 2 valida JSON replay, tamaños en bytes, schema, identidad del caso y procedencia del motor. Estos contratos permiten traer otra tabla de observaciones sin cambiar el experimento en silencio.' },
] };
