"""Derive report tables and reproducibility hashes from the committed numerical artifacts."""
import hashlib
import json
from pathlib import Path

root=Path(__file__).resolve().parents[1]
data=root/'data/derived/v2'
cat=json.loads((data/'catalog.json').read_text(encoding='utf-8'))
training=json.loads((data/'models/training.json').read_text())
rows=[]
for case in cat['cases']:
    v=case['variants'][0]
    for method,m in v['methods'].items():
        rows.append(dict(case=case['id'],family=case['family'],method=method,metrics=m['metrics']))
summary={'cases':len(cat['cases']),'experiments':sum(len(c['variants']) for c in cat['cases']),'reference_results':rows,'learning':{k:training[k] for k in ['device','gpu','split_counts','cnn_test_mse','classical_test_mse','units']},'source_sha256':{p.relative_to(root).as_posix():hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted((root/'data-pipeline').glob('*.py'))}}
out=root/'docs/validation';out.mkdir(parents=True,exist_ok=True)
(out/'metrics.json').write_text(json.dumps(summary,indent=2),encoding='utf-8')
text=['# Reference-condition results','', 'Generated by `scripts/report_release.py`. All six conditions remain available in the full catalogue. These metrics use different physical units and must not be averaged across families.','', '| Case | Method | Metrics |','|---|---|---|']
for row in rows:
    vals='; '.join(f'{k}={v:.6g}' if isinstance(v,(int,float)) else f'{k}={v}' for k,v in row['metrics'].items())
    text.append(f"| {row['case']} | {row['method']} | {vals} |")
text.extend(['','## Held-out learning evaluation','',f"CNN column MSE: {training['cnn_test_mse']:.6f} {training['units']}. Classical baseline: {training['classical_test_mse']:.6f} {training['units']}. Counts: {training['split_counts']}. Device: {training['gpu']}.",'','The CNN and spatial L2 inverse receive exactly identical seeded noisy test observations and are evaluated against the identical column target. Checkpoint selection, threshold calibration and tests are separate. Neither baseline was exhaustively tuned. These values apply only to this fixed generator distribution.'])
if 'novelty_evaluation' in training:
    detection=training['novelty_evaluation']
    text.extend(['',f"Novelty detection: sensitivity {detection['sensitivity']:.4f}, specificity {detection['specificity']:.4f}, ROC AUC {detection['roc_auc']:.4f}; {detection['false_negative']} missed withheld-family realizations. Reconstruction error is not a general geological novelty certificate."])
(out/'results.md').write_text('\n'.join(text)+'\n',encoding='utf-8')
print('Wrote metrics, source hashes and reference-method result table.')
