import {test,expect,type BrowserContext,type Page} from "@playwright/test";
import {createHash} from "node:crypto";
import {mkdirSync,readFileSync,writeFileSync} from "node:fs";
import {resolve} from "node:path";
import {execFileSync} from "node:child_process";
const origin="http://127.0.0.1:8877", backend=process.env.GEOPHYSICS_MT_QA_BACKEND_ROOT!, python=process.env.GEOPHYSICS_MT_QA_PYTHON!, enabled=process.env.GEOPHYSICS_MT_QA_ENABLE==="isolated-test-only";
const evidence=resolve("node_modules/.mt-qa/evidence"),email="mt-owner@example.org",password="separate actual MT QA password";
mkdirSync(evidence,{recursive:true});
let context:BrowserContext,page:Page,project:string,nativeDataset:string,nativeQc:string,nativeJob:string,layerDataset:string,layerJob:string;
const errors:string[]=[];
test.describe.configure({mode:"serial"});
const combo=(name:string)=>page.getByRole("combobox",{name,exact:true});
async function post(path:string,data?:unknown,form?:Record<string,string>){const csrf=await(await context.request.get(origin+"/api/auth/csrf")).json();return context.request.post(origin+path,{headers:{Origin:origin,"X-CSRF-Token":csrf.csrf_token},...(form?{form}:{data})});}
async function upload(file:string,station:string,count:number,rotation=0,tipper=false,malformed=false){
  let body=readFileSync(file);if(malformed)body=Buffer.from(body.toString().replace(">ZXYR",">UNKNOWN"));
  const metadata={filename:`${station}${malformed?"-invalid":""}.edi`,format:"edi",mime:"text/plain",source:{provider:tipper?"USGS Clear Lake measured EDI":"Original synthetic test control",rights_statement:"Private independent QA control only; no redistribution",rights_decision:"provider-link-only",private_storage_permission:"attested",attribution:"Source owner",expected_bytes:body.length,expected_sha256:createHash("sha256").update(body).digest("hex")},physical:{coordinate_reference:"local",local_crs:"source EDI station coordinates",axis_order:"xy",horizontal_datum:"source EDI frame",vertical_datum:"source EDI elevation",vertical_positive:"up",horizontal_unit:"m",vertical_unit:"m",measurement_unit:"mV/km/nT",epoch_utc:"2026-09-28T00:00:00Z",component_frame:"instrument axes",geometry:{station_id:station,frequency_count:count,tensor_components:["Zxx","Zxy","Zyx","Zyy",...(tipper?["Tx","Ty"]:[])],rotation_degrees:rotation,rotation_reference:"unspecified",sign_convention:"+",variance_convention:"complex"}}};
  const csrf=await(await context.request.get(origin+"/api/auth/csrf")).json();const response=await context.request.post(origin+`/api/projects/${project}/assets`,{headers:{Origin:origin,"X-CSRF-Token":csrf.csrf_token,"Content-Type":"text/plain","X-Asset-Metadata":JSON.stringify(metadata)},data:body});expect(response.ok(),await response.text()).toBe(true);return(await response.json()).asset_id as string;
}
async function envelope(asset:string){await combo("Control section").selectOption("data");await page.getByRole("button",{name:"Refresh MT project",exact:true}).click();await combo("Stored EDI original").selectOption(asset);await page.getByRole("button",{name:"Validate EDI envelope",exact:true}).click();await expect(page.getByTestId("mt-eligibility")).toContainText("API method eligible");return await combo("Validated EDI dataset").inputValue();}
async function run(){const [response]=await Promise.all([page.waitForResponse(r=>r.request().method()==="POST"&&r.url().endsWith(`/api/projects/${project}/jobs`)),page.getByRole("button",{name:"Submit MT job",exact:true}).click()]);expect(response.status()).toBe(202);const admitted=await response.json();await expect(combo("MT job")).toHaveValue(admitted.job_id);await expect(page.getByTestId("mt-job-status")).toHaveText("Succeeded");await expect(page.getByTestId("mt-instrument")).toBeVisible();return admitted.job_id as string;}
async function output(job:string,label:string){const response=await context.request.get(origin+`/api/projects/${project}/jobs/${job}/result`);expect(response.ok()).toBe(true);const result=await response.json();writeFileSync(resolve(evidence,`${label}-result.json`),JSON.stringify(result,null,2));return result;}
async function exportJob(label:string){const [download]=await Promise.all([page.waitForEvent("download"),page.getByRole("button",{name:"Verify & export MT ZIP",exact:true}).click()]);const file=resolve(evidence,`${label}.zip`);await download.saveAs(file);const receipt=execFileSync(python,["-B","-c","import sys,json; from pathlib import Path; from app.bundle import verify_bundle; print(json.dumps(verify_bundle(Path(sys.argv[1]).read_bytes())))",file],{cwd:backend,env:{...process.env,PYTHONPATH:backend,PYTHONDONTWRITEBYTECODE:"1"},encoding:"utf8"});expect(JSON.parse(receipt)).toBeTruthy();writeFileSync(resolve(evidence,`${label}-verified.json`),receipt);}
test.beforeAll(async({browser})=>{
  context=await browser.newContext({viewport:{width:1600,height:900},acceptDownloads:true,hasTouch:true});await context.addInitScript(()=>{if(!localStorage.getItem("caos.lang"))localStorage.setItem("caos.lang","en");if(!localStorage.getItem("caos.theme"))localStorage.setItem("caos.theme","light");});page=await context.newPage();page.on("pageerror",e=>errors.push(e.message));
  const identity=await(await context.request.get(origin+"/__qa/mt")).json();expect(identity.harness).toBe("actual-mt-api-worker/v1");expect(identity.mt_enabled).toBe(enabled);writeFileSync(resolve(evidence,enabled?"backend-enabled.json":"backend-closed.json"),JSON.stringify(identity,null,2));
  expect((await post("/api/auth/register",{email,password})).ok()).toBe(true);const {token}=await(await context.request.get(origin+"/__qa/mail/latest")).json();expect((await post("/api/auth/verify/verify",{token})).ok()).toBe(true);
});
test.afterAll(async()=>{await context?.close();});
test("real owner upload, envelope and default-closed admission or actual M05/M06",async()=>{
  await page.goto(origin+"/");await page.getByRole("button",{name:"Projects & raw data",exact:true}).click();await page.getByLabel("Email",{exact:true}).fill(email);await page.getByLabel("Password",{exact:true}).fill(password);await page.getByRole("button",{name:"Sign in",exact:true}).click();
  await page.getByLabel("Project name",{exact:true}).fill("Actual MT scientific controls");await page.getByLabel("Description",{exact:true}).fill("Isolated actual worker QA; no public activation");await page.getByRole("button",{name:"Create project",exact:true}).click();
  await page.getByLabel("Local original file",{exact:true}).setInputFiles(resolve(backend,"data/fixtures/edi/halfspace-100-native.edi"));await combo("Declared raw format").selectOption("edi");await combo("Coordinate reference").selectOption("local");
  for(const [name,value] of [["Provider or acquisition owner","Original synthetic test control"],["Rights statement and permission basis","Private independent QA control only"],["Required attribution","Original synthetic control"],["Local survey frame definition","source EDI station coordinates"],["Horizontal datum (exact declared name)","source EDI frame"],["Vertical datum","source EDI elevation"],["Acquisition epoch with UTC offset (ISO 8601)","2026-09-28T00:00:00Z"],["Station ID","HALFSPACE_100_NATIVE"],["Frequency count","24"],["Tensor components (comma-separated)","Zxx,Zxy,Zyx,Zyy"],["Rotation (degrees)","0"],["Rotation reference (MT processing: unspecified or geographic-north)","unspecified"],["Time sign (MT processing: + or −)","+"],["Variance convention (MT processing: complex or per-real-component)","complex"]])await page.getByLabel(name,{exact:true}).fill(value);
  for(const [name,value] of [["Public rights decision (does not publish this upload)","provider-link-only"],["Coordinate axis order","xy"],["Positive vertical direction","up"],["Horizontal coordinate unit","m"],["Vertical coordinate unit","m"],["Measurement unit","mV/km/nT"],["Component orientation/frame","instrument axes"]])await combo(name).selectOption(value);
  await page.getByRole("dialog").getByRole("checkbox").check();await page.getByRole("button",{name:"Upload original bytes",exact:true}).click();await expect(page.getByRole("heading",{name:"Owner upload receipt"})).toBeVisible();await page.getByRole("button",{name:"Open processing workbench"}).click();project=new URL(page.url()).searchParams.get("project")!;
  await page.getByRole("button",{name:"MT transfer functions",exact:true}).click();await page.getByRole("button",{name:"Validate EDI envelope",exact:true}).click();await expect(combo("Validated EDI dataset")).not.toHaveValue("");nativeDataset=await combo("Validated EDI dataset").inputValue();
  if(!enabled){await expect(page.getByTestId("mt-eligibility")).toContainText("pending_host_admission");await expect(page.getByRole("button",{name:"Submit MT job",exact:true})).toBeDisabled();const response=await post(`/api/projects/${project}/jobs`,{dataset_id:nativeDataset,method_id:"mt.edi-full-tensor-qc/v1",parameters:{}});expect(response.status()).toBe(409);expect((await response.json()).code??(await response.json()).error?.code).toBe("host_admission_pending");await page.screenshot({path:resolve(evidence,"closed-admission.png")});return;}
  expect((await context.request.post(origin+"/__qa/worker/start")).ok()).toBe(true);nativeQc=await run();const qc=await output(nativeQc,"halfspace-m05");expect(qc.inverse).toBeNull();expect(qc.screen.one_d_inversion_eligible).toBe(true);await exportJob("halfspace-m05");
  await combo("Control section").selectOption("run");await combo("MT method").selectOption("mt.edi-fixed-thickness-trf/v1");await page.getByLabel("Initial layer resistivity [Ω m]",{exact:true}).fill("40");await page.getByLabel("Seed [1]",{exact:true}).fill("71401");nativeJob=await run();const result=await output(nativeJob,"halfspace-m06");const method=result.inverse.methods["mt-lm"];expect(method.model[0]).toBeCloseTo(100,6);expect(result.truth).toBeNull();expect(method.uncertainty.completed).toBe(20);await exportJob("halfspace-m06");
});
test("actual layered parameter effect and immutable scientific controls",async()=>{
  test.skip(!enabled);const asset=await upload(resolve(backend,"data/fixtures/edi/two-layer-noisy-rotated.edi"),"TWO_LAYER_NOISY_ROTATED",24,27);layerDataset=await envelope(asset);await combo("MT method").selectOption("mt.edi-full-tensor-qc/v1");await run();await combo("Control section").selectOption("run");await combo("MT method").selectOption("mt.edi-fixed-thickness-trf/v1");await combo("Imposed geometry").selectOption("two");await page.getByLabel("Initial layer resistivity [Ω m]",{exact:true}).fill("100");await page.getByLabel("β [1]",{exact:true}).fill("0.001");layerJob=await run();const low=await output(layerJob,"layered-low-beta");await exportJob("layered-low-beta");
  await combo("Control section").selectOption("run");await page.getByLabel("β [1]",{exact:true}).fill("0.5");const highJob=await run(),high=await output(highJob,"layered-high-beta");expect(high.request_sha256).not.toBe(low.request_sha256);expect(high.inverse.methods["mt-lm"].model).not.toEqual(low.inverse.methods["mt-lm"].model);expect(low.inverse.evaluation_protocol.thickness_sensitivity).toHaveLength(2);expect(low.inverse.truth).toBeNull();await exportJob("layered-high-beta");
  await combo("MT job").selectOption(layerJob);await expect(page.getByTestId("mt-instrument")).toBeVisible();await combo("Scientific view").selectOption("protocol");await expect(page.getByTestId("mt-fit-metrics")).toContainText(String(low.inverse.methods["mt-lm"].metrics.withheld_component_wrms));
  await combo("Control section").selectOption("run");await page.getByLabel("Fixed thickness h [m]",{exact:true}).fill("420");await page.getByLabel("Seed [1]",{exact:true}).fill("71402");const changedJob=await run(),changed=await output(changedJob,"layered-thickness-seed");expect(changed.parameters.thickness_m).toEqual([420]);expect(changed.parameters.seed).toBe(71402);expect(changed.inverse.active).toEqual(low.inverse.active);expect(changed.inverse.methods["mt-lm"].model).not.toEqual(high.inverse.methods["mt-lm"].model);expect(changed.inverse.methods["mt-lm"].uncertainty.samples).not.toEqual(high.inverse.methods["mt-lm"].uncertainty.samples);await exportJob("layered-thickness-seed");await combo("MT job").selectOption(layerJob);await expect(page.getByTestId("mt-instrument")).toBeVisible();
});
test("linked coordinates, signed residual scales, pointer/keyboard/zoom",async()=>{
  test.skip(!enabled);await combo("Scientific view").selectOption("response");await combo("Response quantity").selectOption("real");const graph=page.getByRole("group",{name:"Observed and predicted response",exact:true});await graph.focus();await graph.press("End");await expect(combo("Selected frequency")).toHaveValue("23");const rect=(await graph.boundingBox())!;await page.mouse.move(rect.x+rect.width*.4,rect.y+rect.height*.5);const i=Number(await combo("Selected frequency").inputValue());const result=await output(layerJob,"pointer-coordinate");await expect(page.getByTestId("mt-frequency-readout")).toContainText(String(result.frequency_hz[i]));
  const before=await graph.getAttribute("data-x-min");await page.mouse.move(rect.x+rect.width*.3,rect.y+rect.height*.4);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.7,rect.y+rect.height*.4);await page.mouse.up();expect(await graph.getAttribute("data-x-min")).not.toBe(before);await graph.press("Escape");expect(await graph.getAttribute("data-x-min")).toBe(before);
  await combo("Horizontal axis").selectOption("period");const periodIndex=Number(await combo("Selected frequency").inputValue());await expect(page.getByTestId("mt-frequency-readout")).toContainText(String(1/result.frequency_hz[periodIndex]));await combo("Horizontal scale").selectOption("linear");await combo("Scientific view").selectOption("residual");const residual=page.getByRole("group",{name:"Signed real residual",exact:true});const ymin=Number(await residual.getAttribute("data-y-min")),ymax=Number(await residual.getAttribute("data-y-max"));expect(ymin).toBe(-ymax);await combo("Residual unit").selectOption("ohm");const rawMax=Number(await residual.getAttribute("data-y-max"));expect(rawMax).not.toBe(ymax);await combo("Impedance plot unit").selectOption("milli");expect(Number(await residual.getAttribute("data-y-max"))).toBeCloseTo(rawMax*1000,7);await combo("Impedance plot unit").selectOption("ohm");await combo("Horizontal axis").selectOption("frequency");await combo("Horizontal scale").selectOption("log");
  expect(await page.getByRole("group",{name:"Signed imaginary residual",exact:true}).getAttribute("data-y-max")).toBe(await residual.getAttribute("data-y-max"));await combo("Scientific view").selectOption("model");await page.locator('.earth-layer[role="button"]').last().click();await expect(page.getByTestId("mt-layer-readout")).toContainText("Selected layer 2");await page.locator('.earth-layer[role="button"]').first().press("Enter");await expect(page.getByTestId("mt-layer-readout")).toContainText("Selected layer 1");
});
test("EN/ES light/dark desktop/phone complete scientific panel screenshot matrix",async()=>{
  test.skip(!enabled);for(const lang of ["en","es"])for(const theme of ["light","dark"])for(const [width,height] of [[1280,800],[1600,900],[2560,1440],[390,844]]){
    await page.setViewportSize({width,height});await page.evaluate(({lang,theme})=>{localStorage.setItem("caos.lang",lang);localStorage.setItem("caos.theme",theme);},{lang,theme});await page.reload();const es=lang==="es";
    if(width===390)await page.getByRole("button",{name:es?"Controles de procesamiento MT":"MT processing controls",exact:true}).click();await combo(es?"Conjunto EDI validado":"Validated EDI dataset").selectOption(layerDataset);await combo(es?"Sección de controles":"Control section").selectOption("history");await combo(es?"Trabajo MT":"MT job").selectOption(layerJob);if(width===390)await page.getByRole("button",{name:es?"Controles de procesamiento MT":"MT processing controls",exact:true}).click();
    await expect(page.getByTestId("mt-instrument")).toBeVisible();const main=page.locator(".processing-main");
    for(const view of ["response","tensor","residual","model","protocol","uncertainty","solver"]){await combo(es?"Vista científica":"Scientific view").selectOption(view);await main.evaluate(el=>{el.scrollTop=0;});await expect(page.getByTestId("mt-frequency-readout")).toBeVisible();await page.screenshot({path:resolve(evidence,`${lang}-${theme}-${width}-${view}-top.png`)});
      const plots=main.locator("svg[role=group]");for(let j=0;j<await plots.count();j++){const svg=plots.nth(j);await svg.scrollIntoViewIfNeeded();const r=(await svg.boundingBox())!;await page.mouse.move(r.x+r.width*.62,r.y+r.height*.5);expect(await svg.getAttribute("data-selected-index")).not.toBeNull();await page.screenshot({path:resolve(evidence,`${lang}-${theme}-${width}-${view}-pointer-${j}.png`)});}
      if(view==="response")for(const quantity of ["phase","real","imag"]){await combo(es?"Magnitud de respuesta":"Response quantity").selectOption(quantity);await main.locator("svg[role=group]").first().scrollIntoViewIfNeeded();await page.screenshot({path:resolve(evidence,`${lang}-${theme}-${width}-response-${quantity}.png`)});}
      if(width===390&&view==="response"){const svg=main.locator("svg[role=group]").first();await svg.scrollIntoViewIfNeeded();const r=(await svg.boundingBox())!;await page.touchscreen.tap(r.x+r.width*.8,r.y+r.height*.5);const selected=await svg.getAttribute("data-selected-index");expect(selected).not.toBeNull();const cdp=await context.newCDPSession(page),before=Number(await svg.getAttribute("data-x-max"))-Number(await svg.getAttribute("data-x-min")),y=r.y+r.height*.5;await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{x:r.x+r.width*.4,y,id:1},{x:r.x+r.width*.6,y,id:2}]});await cdp.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{x:r.x+r.width*.3,y,id:1},{x:r.x+r.width*.8,y,id:2}]});await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});expect(Number(await svg.getAttribute("data-x-max"))-Number(await svg.getAttribute("data-x-min"))).toBeLessThan(before);await cdp.detach();await page.screenshot({path:resolve(evidence,`${lang}-${theme}-${width}-touch-pinch.png`)});}
      if(view==="model"){await main.locator('.earth-layer[role="button"]').last().click();await expect(page.getByTestId("mt-layer-readout")).toContainText(es?"Capa seleccionada 2":"Selected layer 2");await page.screenshot({path:resolve(evidence,`${lang}-${theme}-${width}-model-pointer.png`)});}
      const tables=main.locator('.processing-station-table').filter({visible:true});for(let j=0;j<await tables.count();j++){await tables.nth(j).scrollIntoViewIfNeeded();await page.screenshot({path:resolve(evidence,`${lang}-${theme}-${width}-${view}-table-${j}.png`)});if(width===390){await tables.nth(j).evaluate(el=>{el.scrollLeft=el.scrollWidth;});await page.screenshot({path:resolve(evidence,`${lang}-${theme}-${width}-${view}-table-${j}-right.png`)});}}
      await main.evaluate(el=>{el.scrollTop=el.scrollHeight;});await page.screenshot({path:resolve(evidence,`${lang}-${theme}-${width}-${view}-bottom.png`)});
    }
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  }expect(errors).toEqual([]);
});
test("real cl061 stays QC-only; malformed and cancelled jobs have no result",async()=>{
  test.skip(!enabled);await page.setViewportSize({width:1600,height:900});await page.evaluate(()=>{localStorage.setItem("caos.lang","en");localStorage.setItem("caos.theme","light");});await page.reload();
  const clear=process.env.GEOPHYSICS_MT_QA_CLEAR_LAKE;if(!clear)throw new Error("Explicit private original cl061 path required");const raw=readFileSync(clear);expect(createHash("sha256").update(raw).digest("hex")).toBe("90c5c96cd69d6d29c866a768097cb3b38bc20e8b9c143e24bf10b2d253261e83");
  const asset=await upload(clear,"cl061",42,0,true);await envelope(asset);await combo("MT method").selectOption("mt.edi-full-tensor-qc/v1");const clJob=await run(),cl=await output(clJob,"cl061-m05");expect(cl.inverse).toBeNull();expect(cl.screen.one_d_inversion_eligible).toBe(false);await expect(page.getByTestId("mt-qc-verdict")).toContainText("QC only");await combo("Scientific view").selectOption("tensor");await expect(page.getByRole("table").first()).toContainText("fails");await expect(combo("Scientific view").locator('option[value="model"]')).toHaveCount(0);await exportJob("cl061-m05");await combo("Control section").selectOption("run");await combo("MT method").selectOption("mt.edi-fixed-thickness-trf/v1");await expect(page.getByRole("button",{name:"Submit MT job",exact:true})).toBeDisabled();await page.screenshot({path:resolve(evidence,"cl061-qc-only.png")});
  const bad=await upload(resolve(backend,"data/fixtures/edi/halfspace-100-native.edi"),"HALFSPACE_100_NATIVE",24,0,false,true);await envelope(bad);await combo("MT method").selectOption("mt.edi-full-tensor-qc/v1");await page.getByRole("button",{name:"Submit MT job",exact:true}).click();await expect(page.getByTestId("mt-job-status")).toHaveText("Failed");await expect(page.getByRole("alert")).toContainText("processing_failed");await expect(page.getByTestId("mt-instrument")).toHaveCount(0);await expect(page.getByRole("button",{name:"Verify & export MT ZIP",exact:true})).toBeDisabled();
  expect((await context.request.post(origin+"/__qa/worker/stop")).ok()).toBe(true);await combo("Validated EDI dataset").selectOption(nativeDataset);await combo("Control section").selectOption("run");await page.getByRole("button",{name:"Submit MT job",exact:true}).click();await expect(page.getByTestId("mt-job-status")).toHaveText("Queued");await page.getByRole("button",{name:"Cancel MT job",exact:true}).click();await expect(page.getByTestId("mt-job-status")).toHaveText("Cancelled");await expect(page.getByTestId("mt-instrument")).toHaveCount(0);expect(errors).toEqual([]);
  expect((await post("/api/auth/cookie/logout")).ok()).toBe(true);await page.reload();await expect(page.getByTestId("mt-instrument")).toHaveCount(0);await expect(page.getByRole("button",{name:"Submit MT job",exact:true})).toHaveCount(0);
});
